### ISSUE TITLE
add support for Sessions end-point

### ISSUE THREAD

**Issue by jstjoe** [blakmatrix/node-zendesk#112]
Hello :)

Zendesk recently implemented a server-side sessions store, complete with REST API end-points. Anybody got plans to add these in to node-zendesk?
https://developer.zendesk.com/rest_api/docs/core/sessions

If not I may have a go at it, but wanted to check first (and track here as an issue).

Thanks!

**Comment by erikzrekz** [comment]
@jstjoe we could definitely get this in! Thanks for mentioning it.

**Comment by erikzrekz** [comment]
@jstjoe not sure if you saw this, but there is now `sessions` support -- https://github.com/blakmatrix/node-zendesk/blob/master/lib/client/sessions.js. Closing this out.
