### ISSUE TITLE
Socket hanging up on `.queryAll`

### ISSUE THREAD

**Issue by callumacrae** [blakmatrix/node-zendesk#118]
Hey!

I have this code:

```js
const query = `checkout-failure order_by:created sort:desc`;
zendeskClient.search.queryAll(query, function (err, req, res) {
	console.log(err);
});
```

I'm getting this error:

```
{ [Error: socket hang up] code: 'ECONNRESET' }
```

There are only 550 or so tickets being returned, which is 6 pages of results. Any ideas why it isn't working?

**Comment by didil** [comment]
I think you have the same issue as other users (including me) are getting when using node v4+ https://github.com/blakmatrix/node-zendesk/issues/110 , you might wanna report the issue in the other ticket

**Comment by callumacrae** [comment]
Cool, thanks. Closing this one.
