### ISSUE TITLE
View update doesn't accept data to update

### ISSUE THREAD

**Issue by callumacrae** [blakmatrix/node-zendesk#122]
https://github.com/blakmatrix/node-zendesk#views

It needs some data to update: https://developer.zendesk.com/rest_api/docs/core/views#update-view

Is this a bug or am I doing something wrong?

**Comment by erikzrekz** [comment]
Can you share the code you're using and what exactly you're trying to do? I
can try to help.

**Comment by callumacrae** [comment]
```js
zendeskClient.views.update(1234, { view: { title: "test" }}, function () {
  // etc
});
```

**Comment by erikzrekz** [comment]
@callumacrae this looks like an issue with https://github.com/blakmatrix/node-zendesk/blob/master/lib/client/views.js#L47. 

The view object isn't included in the function signature. I'll mark as a bug so we can update this soon.

**Comment by callumacrae** [comment]
I can send a pull request if that would be easier. Is it just a case of updating the function signature?

```
Views.prototype.update = function (viewID, data, cb) {
  this.request('PUT', ['views', viewID, data], cb);
};
```

**Comment by erikzrekz** [comment]
Yep, that and updating the readme.md (https://github.com/blakmatrix/node-zendesk#views)!

**Comment by erikzrekz** [comment]
@callumacrae this will be updated in the v1.1.9 release - https://slack-files.com/T04LRT0NA-F0VNC4PL0-27e43520b3

**Comment by callumacrae** [comment]
:tada:
