### ISSUE TITLE
Incorrect error handling if "retry-after" header is present

### ISSUE THREAD

**Issue by jstjoe** [blakmatrix/node-zendesk#126]
# Problem

It appears that node-zendesk checks for a 'Retry-After' header on the response from the Zendesk API, and if it finds one it overrides the status code to 429 and uses a specific - and incorrect - error string "Zendesk rate limits 200 requests per minute".
### Details
1. Zendesk will include a 'Retry-After' for more than just 429 errors. Specifically we include one for a 503 error: https://developer.zendesk.com/rest_api/docs/core/introduction#500-range
2. Zendesk's rate limit is not fixed at 200rpm. It differs by account, as well as by end-point. This confusing message should probably be removed as it will rarely be correct.
### Possible Fix

As far as I can tell all of this could be removed so it falls back to the regular error handling: https://github.com/blakmatrix/node-zendesk/blob/09069624e986934c1f408f952c9af70467a0052f/lib/client/client.js#L219-L226
This way a 429 error would return 'Too Many Requests' and a 503 would return 'Service Unavailable', as intended.

**Comment by erikzrekz** [comment]
Thanks @jstjoe. I'll take a look into how we can update this this week.
