### ISSUE TITLE
Client part not loaded (requestAll etc)

### ISSUE THREAD

**Issue by matt-in-a-hat** [blakmatrix/node-zendesk#129]
Has `Client` accidentally been forgotten in the list of parts pulled together by the main lib file ([here](https://github.com/blakmatrix/node-zendesk/blob/master/lib/client.js#L5))?

I was expecting to be able to call `.client.request` as per the readme but it didn't exist.

**Comment by erikzrekz** [comment]
@matt-in-a-hat yeah, definitely an oversight. We can get that in.
