### ISSUE TITLE
Unable to update Custom Field value

### ISSUE THREAD

**Issue by omer321** [blakmatrix/node-zendesk#132]
When running `update(80, {“ticket": {"custom_fields": [{"id": 31186457, "value": false}] }});`

The response returns a JSON object without error and the custom field value does not change.

Please advise.

**Comment by ashevch** [comment]
You have different quotes in the ticket, and also if you are using dropdown menus for that custom field you need to match exactly the tag of predefined value otherwise zendesk api will just drop you changes of custom value without any errors.

**Comment by omer321** [comment]
Awesome!  The different quote was the issue.
