### ISSUE TITLE
Getting List of tickets for Assignee

### ISSUE THREAD

**Issue by casalot** [blakmatrix/node-zendesk#139]
Hi, which method should I use to get a list of tickets assigned to a User? This is the API call: `GET /api/v2/users/{user_id}/tickets/assigned.json`

**Comment by erikzrekz** [comment]
Hey @casalot, can you point me to the documentation for what you're describing? I can only find https://developer.zendesk.com/rest_api/docs/core/users#user-related-information which explains `/api/v2/users/{id}/related.json`

**Comment by RakeshKulangara** [comment]
Show ticket has an endpoint that returns the assigned tickets.

https://developer.zendesk.com/rest_api/docs/core/tickets#show-ticket

```GET /api/v2/users/{user_id}/tickets/assigned.json```
