### ISSUE TITLE
seems to be a problem with jobstatuses.watch(jobStatusID, interval, maxAttempts, cb)

### ISSUE THREAD

**Issue by EXC-BAD-ACCESS** [blakmatrix/node-zendesk#140]
using npm version 1.1.8

jobstatuses.show(jobStatusID) works fine, but when calling jobstatuses.watch(...) i get back an error:

`at Request.init (.../node_modules/node-zendesk/node_modules/request/request.js:286:31)
at new Request (.../node_modules/node-zendesk/node_modules/request/request.js:140:8)
at request (.../node_modules/node-zendesk/node_modules/request/index.js:55:10)
at null._request (.../node_modules/node-zendesk/node_modules/request/index.js:101:12)
at Client.request (.../node_modules/node-zendesk/lib/client/client.js:101:15)
at JobStatuses.show (.../node_modules/node-zendesk/lib/client/jobstatuses.js:20:8)
at getJobStatus (.../node_modules/node-zendesk/lib/client/helpers.js:27:24)
at Timeout.getJobStatusUntilComplete (.../node_modules/node-zendesk/lib/client/helpers.js:23:66)
at Timeout.wrapper (timers.js:408:11)
at tryOnTimeout (timers.js:224:11)
at Timer.listOnTimeout (timers.js:198:5) [Error: Invalid URI "undefined/job_statuses/62583e4f606211a8922c50481ffd177f.json"]`

i dumped self.options to the console just before node-zendesk/lib/client/client.js:101 and get:
`options: {
    "stores": {
        "defaults": {
            "type": "literal",
            "store": {
                "stores": {
                    "defaults": {
                        "type": "literal",
                        "store": {
                            "username": "umm@umm.com",
                            "remoteUri": "https://umm.zendesk.com/api/v2",
                            "oauth": true,
                            "token": "mysecrettoken",
                            "debug": true,
                            "type": "literal"
                        },
                        "mtimes": {},
                        "readOnly": true,
                        "loadFrom": null,
                        "logicalSeparator": ":"
                    }
                },
                "sources": [],
                "type": "literal"
            },
            "mtimes": {},
            "readOnly": true,
            "loadFrom": null,
            "logicalSeparator": ":"
        }
    },
    "sources": [],
    "headers": {
        "Content-Type": "application/json",
        "Accept": "application/json",
        "User-Agent": "node-zendesk/1.1.8 (node/5.10.1)",
        "Authorization": "Basic mysecretauth=="
    },
    "uri": "undefined/job_statuses/4770d1dfd6495f9b2143f0c354836883.json",
    "method": "GET"
}`

where i can see "uri" is set to "undefined..."

in a working jobstatuses.show request options looks like:
`options: {
    "stores": {
        "defaults": {
            "type": "literal",
            "store": {
                "username": "umm@umm.com",
                "remoteUri": "https://umm.zendesk.com/api/v2",
                "oauth": true,
                "token": "mysecrettoken",
                "debug": true,
                "type": "literal"
            },
            "mtimes": {},
            "readOnly": true,
            "loadFrom": null,
            "logicalSeparator": ":"
        }
    },
    "sources": [],
    "headers": {
        "Content-Type": "application/json",
        "Accept": "application/json",
        "User-Agent": "node-zendesk/1.1.8 (node/5.10.1)",
        "Authorization": "Bearer mysecrettoken"
    },
    "uri": "https://umm.zendesk.com/api/v2/job_statuses/6d118ba71c4f9bb92d9213e7d5eb078a.json",
    "method": "GET"
}`

so there is an additional level of nesting going on in the self.options for watch vs show, so i suspect that when you go to build the url you are not able to find remoteUri

**Comment by AppSorcery** [comment]
probably not the correct solution, but: #141

**Comment by erikzrekz** [comment]
@AppSorcery thanks for bringing this up. Yeah, I think your PR solves for this. But the origin really is https://github.com/blakmatrix/node-zendesk/blob/master/lib/client.js#L67. 

We can address how we use `nconf` at a later time since that's sort of the culprit. It's been brought up a bit in another thread (See https://github.com/blakmatrix/node-zendesk/issues/80).

**Comment by erikzrekz** [comment]
@nnabuuu any thoughts on this?
