### ISSUE TITLE
1.1.9 has implicit ES2015 requirement

### ISSUE THREAD

**Issue by trystanj** [blakmatrix/node-zendesk#144]
Seems like the 1.1.9 release has an implicit ES2015 requirement (which is a change) while not bumping semver significantly.

Specifically, [this line](https://github.com/blakmatrix/node-zendesk/commit/42251c0748ae75ff5a872ad60ed13033a92453aa#diff-0474b494224d683ee3c020d040e13f13R59) added Object.assign. This is a [Node v4+ feature](http://node.green/#Object-static-methods), which is a large departure from not having this requirement.

Seems like 1.1.8 -> 1.1.9 was a much bigger change than the version number indicates. I think this method should either be removed or the 1.1.9 release should be reverted and bumped to a more significant version.

**Comment by erikzrekz** [comment]
@trystanj reverted here - https://github.com/blakmatrix/node-zendesk/pull/145. Thanks for pointing it out. 

I don't think I can republish the npm package v1.1.9 (as its been deprecated - https://github.com/npm/npm/issues/8305) so I'm not sure what to do there.

**Comment by trystanj** [comment]
If there are features in 1.1.9 that people have already started relying on, maybe not. You could publish the fixed version as 1.1.10? That would keep everything in 1.1.9 working while fixing the ES2015 thing. Unless, of course, other things in 1.1.9 relied on the reverted code - I'm not familiar enough with the codebase to know. It *looked* like that was mostly a stylistic change?

Thanks for the quick fix, though!

**Comment by joerick** [comment]
+1 on republishing a fixed version as 1.1.10 - even if this is just the same code as 1.1.8 retagged with an updated version number! NPM likes to update modules to the latest 'patch' release, so my server was pulling down a different version from what I developed with, so it died in production >.< I've learned my lesson, I'll lock packages down to exact version numbers from now on, but it might help others too.

**Comment by ghs** [comment]
I am also for republishing. In my case everything burned...

**Comment by trystanj** [comment]
Closing issue as this was fixed a long time ago and republished. Thank you!
