### ISSUE TITLE
Missing locale support for help-center category list

### ISSUE THREAD

**Issue by forsberg1** [blakmatrix/node-zendesk#149]
Is there a reason why this is not implemented? 

If no i can make a fast PR to fix this :)

**Comment by nnabuuu** [comment]
Looks like this is a new supported feature.

I will go through all the docs to see if there is more to be added for helpcenter.

PR is always welcomed : )

Thanks

**Comment by erikzrekz** [comment]
@forsberg1 feel free to up a PR for this.
