### ISSUE TITLE
401 Not Aauthorized

### ISSUE THREAD

**Issue by nishikawa7863** [blakmatrix/node-zendesk#151]
I'm getting a 401 Unauthorized when trying to create a ticket, I'm getting the following message:

Zendesk error:  { [Error: Zendesk Error (401): Not Authorized]
  statusCode: 401,
result: <Buffer 7b 22 65 72 72 6f 72 22 3a 22 43 6f 75 6c 64 6e 27 74 20 61 75 74 68 65 6e 74 69 63 61 74 65 20 79 6f 75 22 7d>,
 retryAfter: null }

I've updated to the latest version, but still getting the same message. It used to work fine, just recently we found this issue. Any ideas what might be causing this?

Thanks

**Comment by erikzrekz** [comment]
@nishikawa7863 could be how you're authenticating yourself. Have any tokens changed? I just made some requests with the recent version and all worked fine.

**Comment by damarnez** [comment]
I have the same Issue, only NODE_ENV=production.

**Comment by nishikawa7863** [comment]
I was never able to get around this. No changes to tokens at all. Tried OAuth as well and was not able to make it work. We're running Meteor, so I'm not sure if the issue might be similar.

**Comment by hf2186** [comment]
Did you change the URL to https://[YOURORG].zendesk.com/api/v2 ?

**Comment by RamanSB** [comment]
> Did you change the URL to https://[YOURORG].zendesk.com/api/v2 ?

That did it for me, thank you!
