### ISSUE TITLE
Authentication not working

### ISSUE THREAD

**Issue by marcelonidal** [blakmatrix/node-zendesk#152]
Hey guys,
I'm in trouble with the api use.

When i try to do an user list, it gets me a 401 forbidden.
When i do an user/me, it returns a guest user.

I'm using the username and token.

When i make a curl request on the terminal, it returns as expected with the defined user.

Is something wrong with the authentication?

Waithing for some help,

Thanks!

**Comment by marcelonidal** [comment]
Hi,
I discovered that i was sending the wrong username, but i still having problems in authentication.

When i authenticate with a password, i have success on the process, but with the token i got no luck.

PS: Now even with curl the token isnt working.

If someone could help i would be greatful,

Thanks!

**Comment by erikzrekz** [comment]
Hey @marcelonidal, I haven't had any problems authenticating. Might be that how you're creating Zendesk is incorrect. Or it might be a permissions thing. Check if the token is active.

**Comment by erikzrekz** [comment]
Since this isn't an issue with the library, I'm going to close out.
