### ISSUE TITLE
Create user with default password

### ISSUE THREAD

**Issue by viniciuszambotti** [blakmatrix/node-zendesk#157]
Hi. This is not a issue, but I would like to know if I can create a user with a default password. If I can, please tell me how.

Tks.

**Comment by erikzrekz** [comment]
It looks like it's possible with the API (See: https://developer.zendesk.com/rest_api/docs/core/users#set-a-users-password)

However, it doesn't look like it's supported yet.

**Comment by ycpatel813** [comment]
Hi 
Can I know that is zendesk has updated their API? because lots of api are miss match with this module?
I will surely help to support for set a user password.

Thank you.
