### ISSUE TITLE
Does updateMany for Tickets support both types of calls?

### ISSUE THREAD

**Issue by jbcoder** [blakmatrix/node-zendesk#161]
I'm looking at using the ticket `updateMany` function to update many tickets--each with a different field value. I noticed in the Zendesk documentation that there are two ways to use this call. You can either update many tickets with one field change or update many--each with a different field change. I'm working on doing the latter. Does this API support this kind of call? If so, do you have an example of how that would work?

**Comment by jbcoder** [comment]
I've looked into the code and it looks like the `updateMany` function for users may support both types of syntax though the function for tickets doesn't support it. Would this be something that would be easy to implement?

**Comment by erikzrekz** [comment]
@jbcoder You'll have to write that programmatically. What you want is something like a 

```
for i in arr
  tickets.update(arr[x].id, field_changes)
```

**Comment by jbcoder** [comment]
@erikzrekz Thanks! I should have updated this. I found a workaround by changing the `updateMany` function to this:

    Tickets.prototype.updateMany = function (ticket_ids, ticket, cb) {
      var args = Array.prototype.slice.call(arguments);
      if (args.length == 2) {
        cb = ticket;
        ticket = ticket_ids;
        this.request('PUT', ['tickets', 'update_many'], ticket, cb);
      } else if (!ticket_ids) {
        this.request('PUT', ['tickets', 'update_many'], ticket, cb);
      } else {
        this.request('PUT', ['tickets', 'update_many', '?ids=' + ticket_ids.toString()], ticket, cb);
      }
    };
