### ISSUE TITLE
attachments.upload gives 'write after end' error sporadically when promisified using Bluebird

### ISSUE THREAD

**Issue by NarrativeProgramming** [blakmatrix/node-zendesk#162]
When using Promise.promisify on `attachments.uploads`, `write after end` is thrown unpredictably.

**Comment by cahva** [comment]
I can confirm this but I think this error must be deeper inside zendesk api as this error have risen only recently and we have been using version 1.1.8 of node-zendesk for a long time.

**Comment by erikzrekz** [comment]
Thanks for report. Someone will take a look!

**Comment by pmig** [comment]
@erikzrekz any news on this topic?

**Comment by rlemaire** [comment]
I have the same problem.

**Comment by rlemaire** [comment]
The commit of @mdemin914 solves the problem (if you have the file in memory)

**Comment by GitTristan** [comment]
same issue

**Comment by ddesna** [comment]
It could be related with this one https://github.com/blakmatrix/node-zendesk/issues/261
