### ISSUE TITLE
WARNING in ./~/node-zendesk/lib/client.js

### ISSUE THREAD

**Issue by adamleithp** [blakmatrix/node-zendesk#164]
I'm trying to use the API in my webpack project and when I use your example:

var fs = require('fs');
var zendesk = require('node-zendesk');

var client = zendesk.createClient({
  username:  'xxx',
  token:     'xxx',
  remoteUri: 'xxx'
});

I get console warnings 

WARNING in ./~/node-zendesk/lib/client.js
Critical dependencies:
85:17-54 the request of a dependency is an expression
 @ ./~/node-zendesk/lib/client.js 85:17-54

WARNING in ./~/nconf/~/yargs/lib/parser.js
Critical dependencies:
325:23-71 the request of a dependency is an expression
 @ ./~/nconf/~/yargs/lib/parser.js 325:23-71

WARNING in ./~/center-align/utils.js
Critical dependencies:
8:34-41 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/center-align/utils.js 8:34-41

Is there an issue with my webpack loaders or am I missing something important after I npm install the API package?? Anyone know?

**Comment by erikzrekz** [comment]
I don't think it's an issue with this repo. Seems related to this: https://github.com/webpack/webpack/issues/196.
