### ISSUE TITLE
Issue with nested calls

### ISSUE THREAD

**Issue by msv** [blakmatrix/node-zendesk#167]
Hi,

I'm having an issue with nesting calls, specifically, uploading an attachment and on success, creating a new ticket which includes the upload's token. Something like:

```
client.attachments.upload(file, { filepath: 'dog.jpg' }, function () {
  // if no error  
  client.tickets.create(ticket, function () {
    res.status(200).end();
  }
}
```

Upon server start, both calls work. However, for every other subsequent call, the upload returns a 201, but a blank image (width/height: null). The ticket creation returns a 201, but the attached image is blank.

After a lot of trial and error, removing multer, removing express, trying to isolate the issue, I think it may be an issue with the callback logic. Something is not completing properly and causing subsequent uploads to return blank images, maybe because it can't read the files properly when uploading.  The uploads and ticket creation calls themselves work, but like I said the attachment is blank. Restarting the server gets you back to square 1: first time works, others don't.

Switching to using request and manually crafting the http requests works without any problems.

Hope this helps find any bugs!

**Comment by erikzrekz** [comment]
Great. Thanks for the report! Someone will take a look soon!

**Comment by xcarpentier** [comment]
Any update ?

**Comment by Thinkdiff** [comment]
could you please let me know what we have to put instead of this "(file, { filepath: 'dog.jpg' }"  ?
What is in "file" object?
Should I put an address that Uploaded on my server in "filepath" or not? Should I use multer?
