### ISSUE TITLE
Unitary tests

### ISSUE THREAD

**Issue by willsnake** [blakmatrix/node-zendesk#172]
Is it any actual unitary test?
Or is planned to do the unitary test?
Because I couldn't find any on the test files.
[pass-test.js](https://github.com/blakmatrix/node-zendesk/blob/master/test/pass-test.js)

**Comment by willsnake** [comment]
stop hardcoding baka

**Comment by erikzrekz** [comment]
Hey @willsnake, yeah, there aren't any tests yet. If you'd like to contribute to the project, please feel free to submit a PR!
