### ISSUE TITLE
"Unexpected token Y" instead of proper rate limit error

### ISSUE THREAD

**Issue by juicetin** [blakmatrix/node-zendesk#182]
Hi,

I encountered a problem today where the library would randomly fail, and only realised after a while it was due to rate limiting (a 'You exceeded your rate limit' message of some sort).

Here is the error:
```
Uncaught Error: SyntaxError: Unexpected token Y in JSON at position 0
 at _api.then.fail (node_modules/slackbots/index.js:43:33)
 at Array.<anonymous> (node_modules/vow/lib/vow.js:749:56)
 at Immediate.callFns [as _onImmediate] (node_modules/vow/lib/vow.js:24:35)
```

I think instead of a generic (and quite possibly misleading to many) error that is passed back up uncaught, the specific case of rate limits should be handled properly.

**Comment by blakmatrix** [comment]
ref https://github.com/blakmatrix/node-zendesk/issues/126
