### ISSUE TITLE
snyk alert - Uninitialized Memory Exposure

### ISSUE THREAD

**Issue by eran10** [blakmatrix/node-zendesk#199]
node-zendesk@1.2.0 › request@2.74.0 › tunnel-agent@0.4.3

tunnel-agent is HTTP proxy tunneling agent. Affected versions of the package are vulnerable to Uninitialized Memory Exposure.

A possible memory disclosure vulnerability exists when a value of type number is used to set the proxy.auth option of a request request and results in a possible uninitialized memory exposures in the request body.

This is a result of unobstructed use of the Buffer constructor, whose insecure default constructor increases the odds of memory leakage.

i think you guys need to update request to latest version ASAP

**Comment by blakmatrix** [comment]
👍

**Comment by eran10** [comment]
is there any fix coming soon ?

**Comment by Saravanan90** [comment]
+1

**Comment by erikzrekz** [comment]
Yes, sorry for the delay.
