### ISSUE TITLE
Promise Support

### ISSUE THREAD

**Issue by ckknight** [blakmatrix/node-zendesk#202]
Promises are the standard modern way to deal with asynchrony in JavaScript. It would be useful to have first-class Promise support in `node-zendesk`.

This is a dupe of #156, which was closed without explanation.

**Comment by fmsouza** [comment]
In my company we have been using this lib intensively, and the lack of Promise support was causing a lot of trouble for us. So I just pushed a PR with support for Promises in https://github.com/blakmatrix/node-zendesk/pull/237.

**Comment by ajmueller** [comment]
For those who happen upon this issue (and in case #237 is yet to be merged when you find this), you can add Promise support to individual functions using [custom promisified functions in Node](https://nodejs.org/api/util.html#util_custom_promisified_functions).

```javascript
const zendeskClient = zendesk.createClient({
	username: process.env.ZENDESK_USERNAME,
	token: process.env.ZENDESK_TOKEN,
	remoteUri: 'https://example.zendesk.com/api/v2',
});
zendeskClient.tickets.create[promisify.custom] = ticket => {
	return new Promise((resolve, reject) => {
		zendeskClient.tickets.create(ticket, (err, req, result) => {
			if (err) {
				return reject(err);
			}

			resolve([req, result]);
		});
	});
};
const createZendeskTicket = promisify(zendeskClient.tickets.create);
```

How you decide to resolve your Promise is up to you.  I decided to resolve to an array with both variables returned by the client in an array.  This allows you to do the following in an `async` function:

```javascript
const ticket = {
	ticket: {
		subject: `Promisified Ticket`,
		comment: {
			html_body: `<p>Help!</p>`,
		},
		requester: {
			name: `John Smith`,
			email: `johnsmith@example.com`,
		},
	},
};

const [status, createdTicket] = await createZendeskTicket(ticket);
```

**Comment by claydegruchy** [comment]
Here is a very simple generic promisifyer:
```
var promiseClient = (command, ...args) =>
    new Promise((resolve, reject) => {
        var commands = command.split('.')
        command = client[commands[0]][commands[1]]


        args = args.slice(0, command.length - 1)
        args.push((err, req, result) => {
            if (err) reject(err)
            resolve(result)
        })

        client[commands[0]][commands[1]](...args)


    })


//usage
promiseClient('groups.create', { "group": { "name": "My Group" } })
    .then(console.log)
```
