### ISSUE TITLE
Support latest API

### ISSUE THREAD

**Issue by EdByrnee** [blakmatrix/node-zendesk#204]
Zendesk's API has now been updated and allows for access management of articles through segements instead of through tags.

Update the package to support the latest version of Zendesk's API

**Comment by erikzrekz** [comment]
Can you specify which APIs you'd like to see supported? I haven't kept up with the news ones.

**Comment by EdByrnee** [comment]
The help center API to be fully supported specially user segments as this is critical as to how articles are now managed.
