### ISSUE TITLE
Vulnerable dependencies

### ISSUE THREAD

**Issue by Saravanan90** [blakmatrix/node-zendesk#205]
✗ Medium severity vulnerability found on tunnel-agent@0.4.3
- desc: Uninitialized Memory Exposure
- info: https://snyk.io/vuln/npm:tunnel-agent:20170305
- from: node-zendesk@1.2.0 > request@2.74.0 > tunnel-agent@0.4.3
Upgrade direct dependency request@2.74.0 to request@2.81.0 (triggers upgrades to tunnel-agent@0.6.0)

**Comment by erikzrekz** [comment]
Thanks for the update here!
