### ISSUE TITLE
Unable to search promoted articles with searchArticles

### ISSUE THREAD

**Issue by DaveyEdwards** [blakmatrix/node-zendesk#207]
I have been unable to only get back articles that are set to promoted: true using searchArticles, it just returns 0 results. I think its likely I have just been trying the wrong way, but I think the documentation on using searchArticles may need a example for others that may run into this.

One variation of what I have been trying to do is below (been trying everything I can think of)
_Note: I could add this as an example for the example folder after fixed_
```js
var exampleConfig = require('./exampleConfig');
var fs = require('fs');
var zd = require('../lib/client');

var client = zd.createClient({
  username:  exampleConfig.auth.username,
  token:     exampleConfig.auth.token,
  remoteUri: `https://${yourDomainHere}.zendesk.com/api/v2/help_center`,
  helpcenter: true,
});

client.search.searchArticles('promoted=true', function (err, req, result)
  if (err) {
    console.log(err);
    return;
  }
  console.log(result);
});
```

Other inputs I have tried to the searchString are: 'promoted_articles', 'promoted_articles=true', {promoted: true}.

I also was trying with the following config with no luck, thinking it should not be using the help_center remoteUri/helpcenter: true properties
```js
var client = zd.createClient({
  username:  exampleConfig.auth.username,
  token:     exampleConfig.auth.token,
  remoteUri: `https://${yourDomainHere}.zendesk.com/api/v2`,
});
```

Any help would be greatly appreciated, thanks.

**Comment by hdemirev** [comment]
The Zendesk help center search API doesn't support 'promoted' as a search parameter; you can see all of the supported parameters [here](https://developer.zendesk.com/rest_api/docs/help_center/search.html). 

You could use `articles.list` to get all the articles, and then just filter by the promoted status returned in the results.

**Comment by DaveyEdwards** [comment]
Ahh ok, thanks for the heads up.  Yeah I was thinking to just do the filtering on the server, my only concern was when there are lots of articles it may be hard to get a list of promoted ones to display.  Another solution that just came to mind while typing this would be to create a section called promoted and place all the articles we want promoted in there.
