### ISSUE TITLE
documentation for the callback parameters?

### ISSUE THREAD

**Issue by mrcoles** [blakmatrix/node-zendesk#210]
Is there more info on what the callback parameters are for the API methods?

The only relevant thing I see in the readme is:

```
client.users.list(function (err, req, result) {
  if (err) {
    console.log(err);
    return;
  }
  console.log(JSON.stringify(result[0], null, 2, true));//gets the first page
});
```

Looking into the code, e.g., [client.js requestCallback](https://github.com/blakmatrix/node-zendesk/blob/179dcd735624b5a899b4f8ec17c92a5c80275879/lib/client/client.js#L261), and via running the code, I see that the values are:

*   err - error object from the request package
*   req - number - the status code of the response (if no error)
*   result - plain object or array - the parsed json data from the result (if no error)

Some ideas:

1.  Info about the callback parameters could be put directly under the [Core API Methods](https://github.com/blakmatrix/node-zendesk#core-api-methods) header in the README
2.  You could rename `req` to `statusCode`
3.  You could have client.js requestCallback include the response.statusCode in the error case too? (or is response not defined in that case? Maybe safer would be `response && response.statusCode`)

Just some suggestions! Thanks for making this library.

**Comment by erikzrekz** [comment]
Good suggestions. I'm in favor of better documentation (so your first idea) to start.
