### ISSUE TITLE
Subdomain

### ISSUE THREAD

**Issue by pnewell** [blakmatrix/node-zendesk#212]
I can't seem to get the subdomain option to work (note: I tried both with and without  `disableGlobalState: true`)

```
var zendesk = require('node-zendesk');

var client = zendesk.createClient({
  subdomain: 'MYSUBDOMAIN',
  username:  'MYUSERNAME',
  password:  'MYPASSWORD',
  disableGlobalState: true,
  helpcenter: true
});

client.articles.list(function (err, statusList, body, responseList, resultList) {
  if (err) {
    console.log(err);
    return;
  }
  console.log(JSON.stringify(body, null, 2, true));//will display all tickets
});
```

Error:
`Error: Invalid URI "undefined/articles.json"`

**Comment by hdemirev** [comment]
What's an example of the subdomain value you're entering?

**Comment by pnewell** [comment]
```
var client = zendesk.createClient({
subdomain: 'appleorange',
```
A single string, all lowercase, no special characters, numbers or spaces, just letters

**Comment by hdemirev** [comment]
Try using this configuration: 
```
var client = zendesk.createClient({
  username:  'USERNAME',
  password: 'PASSWORD',
  remoteUri: 'https://SUBDOMAIN.zendesk.com/api/v2/help_center',
  helpcenter: true
});
```

**Comment by pnewell** [comment]
That works, I was more just wondering why the subdomain route wasn't working. I looked at the client.js file, and the code is there to create the URI from the subdomain, but it doesn't seem to be working for some reason...

**Comment by hdemirev** [comment]
Looking more closely, it doesn't seem like nconf is configured correctly in client.js, in line 58 nconf.get returns undefined. I'm not super familiar with how nconf works, but if you override it in client.js like `nconf.overrides(options)` at line 55 the subdomain option works.

**Comment by pnewell** [comment]
Thanks for that, it worked!

Can we open a bug somehow to get it added to the master?
