### ISSUE TITLE
this.request is not a function

### ISSUE THREAD

**Issue by mirandashort** [blakmatrix/node-zendesk#216]
`"node-zendesk": "^1.2.1"`
`"request": "^2.85.0"`

This is my function: 

```
  async.waterfall([
    async.apply(exports.csvToJSON, file),
    async.apply(credentials.config.tickets.updateMany, 3280805)
  ], function(err, result) {
    console.log(err, result);
  })
```

when I run my function on the command line, this is the output: 

```
/Users/mirandashort/zendesktool/node_modules/node-zendesk/lib/client/tickets.js:90

  this.request('PUT', ['tickets', 'update_many', '?ids=' + ticket_ids.toString()], ticket,  cb);
       ^

TypeError: this.request is not a function
    at Tickets.updateMany (/Users/mirandashort/zendesktool/node_modules/node-zendesk/lib/client/tickets.js:90:8)
```

I'm not sure why I'm getting this response now, as I have previously been able to call the API successfully. I updated my package and afterwards even installed the `request` package individually just in case. For additional reference, this is lin 90 in the `tickets.js` file (as part of the node-zendesk package)

```
Tickets.prototype.updateMany = function (ticket_ids, ticket, cb) {
  this.request('PUT', ['tickets', 'update_many', '?ids=' + ticket_ids.toString()], ticket,  cb);
};
```

And lastly, I made sure that `request` was not established as a variable anywhere else. 

Any thoughts on why this is happening? It doesn't seem to be an issue anywhere on stackoverflow..

**Comment by jcrobak** [comment]
I ran into this problem yesterday, and my solution is to bind the appropriate `this` when passing around a function, e.g.:

```
    async.apply(credentials.config.tickets.updateMany.bind(credentials.config.tickets), 3280805)
```

That makes `this` for `updateMany` to be the singleton class `credentials.config.tickets`.

**Comment by josephmcasey** [comment]
Does the author of this library believe this is something worth fixing?
