### ISSUE TITLE
ECONNRESET error on lib but curl works

### ISSUE THREAD

**Issue by geshan** [blakmatrix/node-zendesk#221]
We are using `node-zendesk` version `1.1.8`  also tried the latest version but got the same error.

### Request:

```
var zendesk = require('node-zendesk');
 
var client = zendesk.createClient({
  username:  'user',
  token:     'token',
  remoteUri: 'https://remote.zendesk.com/api/v2',
  debug: true
});
 
client.users.list(function (err, req, result) {
  if (err) {
    console.log(err);
    return;
  }
  console.log(JSON.stringify(result[0], null, 2, true));//gets the first page
});
```

## Response

```
{ Error: read ECONNRESET
    at _errnoException (util.js:1003:13)
    at TLSWrap.onread (net.js:620:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
```

but curl with 

```
curl -i https://namshisupport.zendesk.com/api/v2/users.json -u user/token:longToken
```

It works and gives back json result.

**Comment by boatmeme** [comment]
@geshan any idea when this change will be published as a new version in npm?

**Comment by geshan** [comment]
Depends on @blakmatrix.

**Comment by alexloi** [comment]
Just keeping a note here, this seems to be related to the TLS 1.2 move Zendesk performed earlier today (just in case anyone drops onto this)

**Comment by ssonlucera** [comment]
I get this error.
```{ Error: write EPROTO 1:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:s23_clnt.c:802:

    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:812:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }```

**Comment by blakmatrix** [comment]
Try v1.3.0

**Comment by zfeng8** [comment]
@ssonlucera I got the same issue

**Comment by zfeng8** [comment]
@blakmatrix I tried, but it did not work

**Comment by geshan** [comment]
@zfeng8 try using version 1.3.0.

**Comment by zfeng8** [comment]
@geshan thanks for your response. It did not work for me with 1.3.0

**Comment by JamyDev** [comment]
1.3.0 is working fine here after seeing the same issue. Thanks @blakmatrix .

One question though, why was TLS 1.2 explicitly disabled in the first place?

**Comment by JamyDev** [comment]
Ah I see the comment in [this commit](https://github.com/blakmatrix/node-zendesk/commit/64c3139e103d93a6d4b0d69d5d223c8cac5aa0a7) refer to [this NodeJS issue](https://github.com/nodejs/node-v0.x-archive/issues/5360) back in 2013. While I can't seem to find an exact reason, I assume back then node started to support TLS 1.2 but Zendesk did not yet, forcing you to disable it?

**Comment by JediYozh** [comment]
I got the same error in 1.2.1. Worked for me in 1.3.0

**Comment by oakcreations** [comment]
Worked for me in 1.3.0

**Comment by zfeng8** [comment]
Thanks for all you guys help. Now 1.3.0 works for me. I think that was because I forgot to remove the node_modules folder, and the program still uses the same package even if I changed to 1.3.0. After removing the node_modules and changed to 1.3.0, everything works. Thanks again for saving my day

**Comment by blakmatrix** [comment]
Just wanted to reference pull #223 before I close...
