### ISSUE TITLE
 Cannot read property 'SSL_OP_NO_TLSv1' of undefined

### ISSUE THREAD

**Issue by jonhill04** [blakmatrix/node-zendesk#226]
I just upgraded to v1.3.0, but now instead of the ECONNRESET error I'm getting a 'Cannot read property 'SSL_OP_NO_TLSv1' of undefined' error.  Is anyone else running into this? Any config steps that I missed with the upgrade?  

Any help would be greatly appreciated, as we are currently line down!

**Comment by jreida** [comment]
@jonhill04 this is a node version issue. See https://github.com/blakmatrix/node-zendesk/pull/223#issuecomment-398965029. I went to v8.11, but anything after and including v6.14.3 should work.

**Comment by jonhill04** [comment]
thanks @jreida - I noticed that shortly after my post....still an issue as we are back on Node v4.X, and I don't think it's going to be trivial to jump.  I was hoping there would be a backwards compatible option!

**Comment by hdemirev** [comment]
@jonhill04 I had originally implemented a [different fix here](https://github.com/hdemirev/node-zendesk/commit/83705bc8a71c12ab9779864dbff931751f4975f9), which is Node 4 compatible, and you could pull [from here](https://github.com/hdemirev/node-zendesk) or implement yourself.

**Comment by jonhill04** [comment]
thanks @hdemirev - I'll give that a shot!

**Comment by jonhill04** [comment]
@hdemirev - that's working great, thanks!  Now I can take my time to upgrade Node...
