### ISSUE TITLE
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

### ISSUE THREAD

**Issue by phanssens1** [blakmatrix/node-zendesk#227]
Trying to use multiple versions of the version prior to the latest - this attempt on 1.1.13 renders the following result:
```javascript
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
```

I'm making the following call:

```javascript
client.users.createOrUpdateMany(users, function (err, req, result) {
    if (err) {
      console.log(err);
      return;
    }
    client.jobstatuses.watch(result["job_status"].id, 500, 5, function(err, req, result){
        if (err) {
             console.log(err);
        }
      console.log(JSON.stringify(result, null, 2, true));
    });
  });
```

Any help would be much appreciated

**Comment by prokyon** [comment]
The same problem here on 1.2.1 with this request:

````js
client.users.list(function (err, req, result) {
    if (err) {
        console.log(err)
        return
    }
    console.log(JSON.stringify(result[0], null, 2, true)) // gets the first page
})
````

````js
{ Error: read ECONNRESET at _errnoException (util.js:1022:11) at TLSWrap.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
````

**Comment by thucnc** [comment]
I got the same problem. This issue is critical for us since we are using webhook triggers to automate some processes. Please help.

**Comment by prokyon** [comment]
With version 1.3.0 the connection is working.

**Comment by phanssens1** [comment]
I’ve reported an issue with 1.3.0 as well: https://github.com/blakmatrix/node-zendesk/issues/228

**Comment by jonnyarnold** [comment]
My guess is that this is also related to Zendesk [removing support of old versions of TLS](https://support.zendesk.com/hc/en-us/articles/360000710347).

**Comment by phanssens1** [comment]
using node version 8.10.0 this works - wasn't working on node 6.10.3
