### ISSUE TITLE
Allow for additional query parameters e.g. sort_by

### ISSUE THREAD

**Issue by jleeothon** [blakmatrix/node-zendesk#235]
If I'm not mistaken, there is no way to add other query arguments except with e.g.

```javascript
const myClient = zendesk.createClient(...);
myClient.search.requestAll('GET', ['endpoint', {sort_by: 'date_created'}])
```
Note that in this case, it is superfluous to use the `search` member, and it could by anything e.g. `.tickets.requestAll()` or `.users.requestAll()`.

I can think of two solutions that can mitigate this problem:

(a) A more generic interface for custom requests without going to one of `myClient`'s members. I.e. `myClient.requestAll()` is not defined, if I'm not mistaken.

(b) In general, allow for an optional parameter to all GET methods such that they can be called with e.g.

```javascript
const myClient = zendesk.createClient(...);
myClient.search.query(
  'requester:someId type:ticket',
  {sort_by: 'date_created'}, // this parameter can be omitted
  () => stuff
);
```

What do you think 😃 ?

**Comment by shaun3141** [comment]
I'd love to see something like this too, but I found it's possible still to sort with the query method by passing in search parameters like this:
https://support.zendesk.com/hc/en-us/articles/203663226-Zendesk-Support-search-reference#topic_lhr_wsc_3v

Which oddly is a bit different than the API, but both seem to work, and these linked work with the default query method so it's a win for me. :)

**Comment by cesarpachon** [comment]
sorry I see this is a ticket closed as completed long time ago, but I can't figure what is the official way of passing additional parameters in the current version.
