### ISSUE TITLE
create tickets api - custom_fields is ignored

### ISSUE THREAD

**Issue by ankitwandx** [blakmatrix/node-zendesk#265]
Here is the ticket object:
>var ticket = {
  "ticket":
    {
      "subject":"My printer is on fire!",
      "comment": {
        "body": "The smoke is very colorful."
      },
      "custom_fields": [{ "id": 34, "value": "I need help!" }]
    }
  };

and here is the ticket created:

>{
  "url": "https://xyz.zendesk.com/api/v2/tickets/12.json",
  "id": 12,
  "external_id": null,
  "via": {
    "channel": "api",
    "source": {
      "from": {},
      "to": {},
      "rel": null
    }
  },
  "created_at": "2020-04-20T22:55:46Z",
  "updated_at": "2020-04-20T22:55:46Z",
  "type": null,
  "subject": "My printer is on fire!",
  "raw_subject": "My printer is on fire!",
  "description": "The smoke is very colorful.",
  "priority": null,
  "status": "new",
  "recipient": null,
  "requester_id": 123,
  "submitter_id": 123,
  "assignee_id": null,
  "organization_id": null,
  "group_id": 123,
  "collaborator_ids": [],
  "follower_ids": [],
  "email_cc_ids": [],
  "forum_topic_id": null,
  "problem_id": null,
  "has_incidents": false,
  "is_public": true,
  "due_at": null,
  "tags": [],
  "custom_fields": [],  <<<<<< Here, the values I sent are ignored
  "satisfaction_rating": null,
  "sharing_agreement_ids": [],
  "fields": [],
  "followup_ids": [],
  "brand_id": 123,
  "allow_channelback": false,
  "allow_attachments": true
}

>

**Comment by thomasfaller** [comment]
I'm able to create a ticket with only 1 custom_field doing like:
```javascript
...,
custom_fields: {
   id: 12345
   value: "something"
},
...
```

but trying to set multiple custom_fields by passing an array of objects like you're doing doesn't seem to work indeed so any insight on how to do that would be greatly appreciated :)
