### ISSUE TITLE
Error when uploading attachment

### ISSUE THREAD

**Issue by kevinNgws** [blakmatrix/node-zendesk#279]
Hi all,
I'm testing to upload an image from AWS S3 bucket to ZenDesk as shown below:
`INFO	{
  AcceptRanges: 'bytes',
  LastModified: 2020-08-29T09:52:09.000Z,
  ContentLength: 145978,
  ETag: '"blahblah"',
  ContentType: 'image/jpeg',
  Metadata: {},
  Body: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ff db 00 84 00 06 06 06 06 07 06 07 08 08 07 0a 0b 0a 0b 0a 0f 0e 0c 0c 0e 0f 16 10 11 10 ... 145928 more bytes>
}`

However, when i tried to call` userClient.attachments.upload(attachment, {filename: 'test.jpeg'})`, it resulted in the following error: 
`INFO	TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ff db 00 84 00 06 06 06 06 07 06 07 08 08 07 0a 0b 0a 0b 0a ...
    at Object.open (fs.js:424:10)
    at ReadStream.open (internal/fs/streams.js:146:13)
    at new ReadStream (internal/fs/streams.js:134:10)
    at Object.createReadStream (fs.js:1888:10)
    at /opt/nodejs/node_modules/node-zendesk/lib/client/client.js:254:10
    at new Promise (<anonymous>)
    at Attachments.Client.requestUpload (/opt/nodejs/node_modules/node-zendesk/lib/client/client.js:238:10)
    at Attachments.upload (/opt/nodejs/node_modules/node-zendesk/lib/client/attachments.js:35:15)
    at /var/task/index.js:21:28
    at new Promise (<anonymous>) {
  code: 'ERR_INVALID_ARG_VALUE'
}`

Do i need to convert the buffer to Uint8array via https://github.com/substack/buffer-to-uint8array#readme?

Help needed! Thanks in advance!

**Comment by kevinNgws** [comment]
I modified my code to ` userClient.attachments.upload(stream, {binary:true, filename: 'test.jpeg'})`. 
stream can be created as shown below:
`var stream = new Readable();
  stream.push(imgBuffer);
  stream.push(null);`

However, the response i got back was HTTP Status Code 201, with no data content.

**Comment by margolisj** [comment]
@blakmatrix I ran into a similar type bug today while using multipart to upload files to a server in memory and then shipping them off to zendesk. Not sure if it is a type issue or a data formatting issue. The example for attachment upload seems to use a string instead of a Buffer.

```
typescript
const f: Buffer = file;
const stream = new Readable();
stream.push(f);
stream.push(null);

const resp = (await zendeskClient.attachments.upload(stream as unknown as Buffer, {
  filename: 'temp.png',
  binary: true
})) as ZendeskUploadResponse;
```

Library is awesome btw.
