### ISSUE TITLE
TicketForms.prototype.show is assigned twice

### ISSUE THREAD

**Issue by cfrome77** [blakmatrix/node-zendesk#302]
The TicketForms show function is assigned to twice for both showing and updating. when calling client.ticketforms.show the `PUT` function version will get called instead of the `GET` function version. This causes an error because the `ticketForm` variable is not defined, and it is calling the wrong function. The function is linked below.

https://github.com/blakmatrix/node-zendesk/blob/b69e783756511583f12b855ded9ad6c792a1b80d/lib/client/ticketforms.js#L21-L29

The following code will produce the error. 
```
const getTicketFormData = async function(client, ticketFormId) {
     try {
         let ticketFormData = await client.ticketforms.show(ticketFormId);
         return ticketFormData;
     }  catch(error) {
         console.log(`Error getting zendesk ticket form by ID ${ticketFormId}`, error.stack);
         throw(error);
     }
}
```
Here is an example of the error produced by the above code.

```
Error getting zendesk ticket form by ID XXXXXXXXXXXXX: ReferenceError: ticketForm is not defined
    at exports.TicketForms.TicketForms.show (/workspace/node_modules/node-zendesk/lib/client/ticketforms.js:28:62)
    at Object.getTicketFormData (/workspace/zendesk_api_helper.js:56:51)
    at Object.exports.handler (/workspace/zendesk_event.js:31:49)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
ReferenceError: ticketForm is not defined
```

**Comment by blakmatrix** [comment]
fixed in #306 306
