### ISSUE TITLE
Example HelpCenter

### ISSUE THREAD

**Issue by mthomas-github** [blakmatrix/node-zendesk#303]
could you make an example for HelpCenter? Or when you say ad -hc or -helpcenter parameter Do I add this when I create client?

**Comment by msucorey** [comment]
When you call createClient add `helpcenter: true` to args and on your `remoteUri`, append '/help_center'.  This creates a help center Client that inherits from base and adds methods found in lib/client/helpcenter (and detailed in docs).

**Comment by mvxt** [comment]
Took me some time to find this - is there a section in the docs somewhere that lists out all the possible arguments you can supply when instantiating client? That'd help alot, unless I'm an idiot and missed it somewhere

**Comment by mvxt** [comment]
Also, the above worked without needing to supply flags at all, and supplying flags `-hc` or `--helpcenter` did not work. Unless I did something wrong, it seems like that portion of the docs is out of date
