### ISSUE TITLE
Search users by external_id

### ISSUE THREAD

**Issue by talha-asad** [blakmatrix/node-zendesk#32]
Zendesk docs have this call, is it possible to directly use the external_id search rather than using it in a query. I think zendesk has specifically optimized the other query.
```
Search Users

GET /api/v2/users/search.json?query={query}

GET /api/v2/users/search.json?external_id={external_id}

Specify a partial or full name or email address as the value of the query attribute. Example: query="Gerry". Specify an id number as the value of the external_id attribute. For more advanced searches of users, use the Search API.

```

**Comment by nicksav** [comment]
Hey guys. Not able to get search working with email or phone:
    client.users.search({phone: phone}, function (err, req, data: any) { 
      callback(null, data); 
    });

Any idea?
