### ISSUE TITLE
Incompatible with esbuild/bundling tools

### ISSUE THREAD

**Issue by adenhertog** [blakmatrix/node-zendesk#324]
Due to dynamic/runtime `requires` (`client.js:95`), tools such as esbuild won't include the runtime libraries when producing a runtime bundle (see also: https://github.com/blakmatrix/node-zendesk/issues/282)

Can these `requires` be done explicitly in order to work properly with these tools?

eg:

```typescript
if (options.stores.defaults.store.helpcenter) {
  require('./client/helpcenter/articles')
  require('./client/helpcenter/sections')
  // ...
} else ...
```

**Comment by blakmatrix** [comment]
@adenhertog could you test if the latest version https://www.npmjs.com/package/node-zendesk/v/4.0.1 solves this?
