### ISSUE TITLE
Zendesk Error (401): Not Authorized

### ISSUE THREAD

**Issue by Rakeshkumar1410** [blakmatrix/node-zendesk#334]
I want to implement your API in Node.js with Single sign-on
JWT method , however I had reached out with your support team and your team has suggested to me use the below npm for the Node.js
Node-zendesk
I have implemented the code as same at our end and host on https but facing the below error message:
“Zendesk Error (401): Not Authorized"
Below error comes after the call this
![image](https://user-images.githubusercontent.com/98870300/156298553-b3962d9a-dbec-4161-b3ee-4e281445562f.png)

Could you suggest to me what is I doing wrong..

Note: I have also used the oauth:false but facing same issue..

**Comment by Onaxim** [comment]
Make sure to specify the full API route for your Zendesk subdomain as the remote URI, like `https://<your-sub-domain>.zendesk.com/api/v2/`.
