### ISSUE TITLE
Prototype Pollution in async

### ISSUE THREAD

**Issue by kr8n3r** [blakmatrix/node-zendesk#341]
The latest possible version that can be installed is 1.5.2 because of the following conflicting dependency:

node-zendesk@2.1.1 requires async@^1.4.0 via nconf@0.11.3
The earliest fixed version is 3.2.2.

**Comment by neztEx** [comment]
+1 to this, there is also prototype pollution in node-zendesk@2.1.1 › nconf@0.11.3.

The earliest fixed version is nconf@0.11.4

**Comment by kr8n3r** [comment]
nconf 0.12 containing a CVE mitigation has been released https://github.com/indexzero/nconf/releases/tag/v0.12.0
