### ISSUE TITLE
Request to migrate library from Offset Based Pagination to Cursor Based Pagination

### ISSUE THREAD

**Issue by eric-at-nocoast** [blakmatrix/node-zendesk#354]
Zendesk currently offers both [offset-based pagination](https://developer.zendesk.com/documentation/api-basics/pagination/paginating-through-lists-using-offset-pagination/) (OBP) and [cursor-based pagination](https://developer.zendesk.com/documentation/api-basics/pagination/paginating-through-lists-using-cursor-pagination/) (CBP) for most API endpoints. CBP offers many performance advantages over OBP and will be the primary method of pagination offered at Zendesk in the near future. In an effort to provide a better, faster experience for our customers we are taking steps to encourage a transition to CBP – starting with the introduction of tighter limits on high-offset OBP requests. 

**What is changing?**

Beginning on August 15, 2023, OBP requests over the first 100 pages (10,000 records) will result in an error message: “400 Bad Request.” In order to request data sets larger than 10,000 records, customers will need to [transition to CBP](https://developer.zendesk.com/documentation/api-basics/pagination/paginating-through-lists-using-cursor-pagination/).

OBP requests for fewer than 100 pages will not be affected, nor will requests made using the CBP model.  

**Why is Zendesk making this change?**

We are making this change in line with our [previous announcement](https://support.zendesk.com/hc/en-us/articles/4408846180634-Introducing-Pagination-Changes-Zendesk-API#h_01F7Y57A0G5M3R8JXGCQTBKVWA) recommending adoption of CBP and to encourage customers to make the switch as soon as possible. Not only is cursor-based pagination faster and more efficient for our customers, it also puts less strain on Zendesk infrastructure and increases stability and reliability. As a first step, we are limiting offset-based pagination capabilities at a relatively high level, so that the transition can take place with minimal disruption to current API usage. 

**What do I need to do?**

Zendesk strongly encourages library maintainers to make the transition to cursor-based pagination before August 15, 2023. If you decide to not transition your library please add documentation in regards to the 100 page OBP limit to your library. If we have not heard from you in regards to this change prior to  August 15, 2023. We will be removing our reference to your library from our documentation and will consider it abandoned / unmaintained.

**Comment by gkatechis** [comment]
Hi again from Zendesk! I wanted to follow up on this because it looks like the changes haven't been pushed yet. As a reminder, on August 15, 2023, OBP requests over the first 100 pages (10,000 records) will result in an error message: “400 Bad Request.” In order to request data sets larger than 10,000 records, you will need to [transition to CBP](https://developer.zendesk.com/documentation/api-basics/pagination/paginating-through-lists-using-cursor-pagination/).
