### ISSUE TITLE
What changed in version 3.0.0?

### ISSUE THREAD

**Issue by catamphetamine** [blakmatrix/node-zendesk#357]
Hi.
There doesn't seem to be no CHANGELOG or description on the Releases tab.
So what has changed in version 3.0.0?
Is there anything breaking, as semantic versioning suggests?

**Comment by cryptomail** [comment]
A few things changed.
1. support for users.tags
2. blanket support for cursor based pagination.
Currently the package is broken but https://github.com/blakmatrix/node-zendesk/pull/358 fixes that hopefully.
I added a examplest for it :)

**Comment by blakmatrix** [comment]
I deemed the cursor-based pagination a significant enhancement, possibly involving no direct backward compatibility alterations. However, due to its substantial impact on the library's fundamental operation, I chose not to take any chances, prioritizing stability and seamless integration.
