### ISSUE TITLE
Can't disable reading process.argv and process.env (really?)

### ISSUE THREAD

**Issue by deoxxa** [blakmatrix/node-zendesk#36]
First off, it's a little bit insane to read global state from inside a library, but ignoring that, it's even more insane to not provide a way to disable that behaviour. This reminds me of [this systemd bug](https://bugs.freedesktop.org/show_bug.cgi?id=76935).

As it happens, I have an application that reads its own command-line arguments and uses some of the same flags as this... Library. This third-party library that, without prompting, reads `process.argv` and `process.env`. Ugh.

Anyway. It'd be great if there were a way to disable this. I'll probably put together a pull request later on or something.

**Comment by blakmatrix** [comment]
use option in node-zendesk@v1.0.0 `disableGlobalState: true` to achieve this desired effect.
