### ISSUE TITLE
Possibly get betamax wiremocks up and running here.

### ISSUE THREAD

**Issue by cryptomail** [blakmatrix/node-zendesk#361]
We'll have to do a survey of the "landscape" of JS packages....
But I think this library could use a little attention with testing.

Here's how I would do it.
1. Assess what JS betamax wiremock packages exist and pick one
2. Go through the machinations of recording tests with real credentials before release.
3. Check in those recorded cartridges
4. On GH build have a workflow run npm test with our new wiremocks...when NOT presented credentials, they use cartidges recorded!
5. Profit
6. Make changes to lib, let go of the wheel, and let build test status do the driving.  🚗 💨 
7. Profit more.

**Comment by cryptomail** [comment]
https://github.com/nock/nock last commit 2 days ago.... ❇️

**Comment by blakmatrix** [comment]
@cryptomail leaving this here for visibility https://github.com/nock/nock/issues/2397
