### ISSUE TITLE
Migrate HC APIS not listed in previous issue to CBP

### ISSUE THREAD

**Issue by cryptomail** [blakmatrix/node-zendesk#365]
As per https://support.zendesk.com/hc/en-us/articles/5591904358938-New-limits-for-offset-based-pagination HC endpoints have moved to CBP.
Issue https://github.com/blakmatrix/node-zendesk/issues/354
had a very crusty link with **incomplete** data of endpoints.
Ensure above link is used to true up all endpoints...looks like mostly HC affected now.
👇 Old, incorrect message from article.
![Screenshot 2023-08-22 at 7 08 35 PM](https://github.com/blakmatrix/node-zendesk/assets/846177/b24fd69d-24a9-4f5a-b207-0633b8c52004)

**Comment by blakmatrix** [comment]
@cryptomail I think I'm done with my recent refactor, I prepped the codebase for a swapping out of request for another tool, removed dependencies and overall did a cleanup and modernization of the codebase. LMK if you need anything from me or you need me to comb through the HC endpoints
