### ISSUE TITLE
fetch is not defined

### ISSUE THREAD

**Issue by davecoffin** [blakmatrix/node-zendesk#376]
For some reason I am getting the following bug when trying to do a simple call in my node lambda:
```
Error: RequestAll processing failed: Request all failed during fetching: Raw request failed: fetch is not defined
    at Users.requestAll (/{dir}/node_modules/node-zendesk/src/client/client.js:183:13)
```

**Example Code**
```javascript

const zendesk = require("node-zendesk");

const getCreds = () => {
  return {
    username: "MYUSERNAME",
    token: "MYTOKEN",
    remoteUri: "https://MYSUBDOMAIN.zendesk.com/api/v2"
  };
};
export const getZendeskUsers = async (): Promise<any> => {
  const client = zendesk.createClient(getCreds());
  client.users.list().then((result: any) => {
      console.log(result);
      // console.log(JSON.stringify(result[0], null, 2, true)); //gets the first page
    })
    .catch((error: any) => {
      console.log(error);
    });
};

```

- `node-zendesk` version: latest
- Node.js version: 16.x

running on a lambda

I assume its something silly, any help would be appreciated!

**Comment by bbuck** [comment]
The `fetch` function was added in Node 17:

> Added in: v17.5.0

So you won't be able to run 4.0.0 with `fetch` on Node 16

**Comment by blakmatrix** [comment]
@davecoffin fetch was added in `v4` and we updated the package so npm should throw a warning when installing
```json
"engines": {
    "node": ">= 18"
  },
```
Upgrade to node 18 if you can, if that is not possible but you still want to be on the latest node-zendesk you may try using your own provided transport ( ex: https://github.com/blakmatrix/node-zendesk/blob/master/examples/optional-axios-transport.js ), or you will have to downgrade to the `v3.0.3`
