### ISSUE TITLE
OAuth doesn't work

### ISSUE THREAD

**Issue by stefanielauer** [blakmatrix/node-zendesk#390]
**Describe the Bug**
We are trying to authenticate via Oauth but keep getting Error: Request processing failed: Raw request failed: Missing credentials for Basic Authentication.

**Example Code**
```typescript
import {createClient as zendeskCreateClient} from 'node-zendesk'
const client = await zendeskCreateClient({
        endpointUri: "https://subdomain.zendesk.com",
        token: "xxx",
        oauth: true
    })
client.search.query("some query")
```

**Expected Behavior**
Client authenticates with OAuth and executes the call.

**Actual Behavior**
Execution fails with Error: Request processing failed: Raw request failed: Missing credentials for Basic Authentication.

**Environment Information**
- `node-zendesk` version: 5.0.1
- Node.js version: v19.7.0
- Operating System: Mac OS

**Additional Context**
Assumption: the oauth flag from ZendeskClientOptions might not be transferred to ClientOptions when creating the client.

**Comment by blakmatrix** [comment]
@stefanielauer My apologies for the inconvenience. There was indeed a confusion between the old `oauth` property and the new `useOAuth` property. I have updated the code to ensure that either property will work: [see the commit](https://github.com/blakmatrix/node-zendesk/commit/15910e964c699ca38cd79c74c5c7cfd79899ae57).

Additionally, I have updated the example file to reflect the correct way of checking for OAuth.

Please download the [latest version 5.0.2](https://www.npmjs.com/package/node-zendesk/v/5.0.2) of the package, which includes this fix. I believe this should resolve the issue you're facing with OAuth authentication. Feel free to reach out if you encounter any further problems or have additional questions.
