### ISSUE TITLE
version 5.0.2 return Zendesk error 401 while 3.0.3 is ok

### ISSUE THREAD

**Issue by eran10** [blakmatrix/node-zendesk#392]
i am running this simple part of code that work in version 3.0.3

let zendeskClient = zendesk.createClient({
    username: config.zendesk.username,
    token: config.zendesk.token,
    remoteUri: config.zendesk.remote
});

function searchZendeskUser(query) {
    return zendeskClient.users.search({ query });
}

but when running it in 5.0.2 I am getting
RequestAll processing failed: Request all failed during fetching: Zendesk Error (401): Not Authorized

am I missing something? do I need to define something on the user which is new? since it works before so I am not sure what I need to set on him now o make it work again.

thanks

**Comment by kajoseph** [comment]
I ran into a similar issue and the problem seemed to be with callbacks and using `subdomain` instead of `endpointUri` (which appears to have replaced `remoteUri`). Here's an example of my problem code:

```
const client = zd.createClient({
      username: zendeskCreds.user,
      token: zendeskCreds.token,
      endpointUri: zendeskCreds.url
});

client.tickets.show(ticketId, function (err, ticket) {
  // 401 Not Authorized err is returned
});
```
However, this works:
```
const client = zd.createClient({
      username: zendeskCreds.user,
      token: zendeskCreds.token,
      subdomain: zendeskCreds.subdomain
});

const result = await client.tickets.show(ticketId);
```

**Comment by blakmatrix** [comment]
@eran10 try `5.0.5`, I fixed a regression and added a test that should check this in the future! Thanks for creating this issue.

@kajoseph callbacks were removed in version `v4`  in favor of  promises or async/await consistency if I recall correctly
