### ISSUE TITLE
how to set the request rate, meet 204 code when enable throttle in createClient option

### ISSUE THREAD

**Issue by seawin** [blakmatrix/node-zendesk#397]
**Describe the Bug**
see code below, run with midway.
can't get nice response with throttle enable. need config more ?

**Example Code**
```typescript
import { ILogger, Logger, Provide } from '@midwayjs/core';
import { createClient } from 'node-zendesk';

@Provide()
export class ZendeskService {
  @Logger()
  logger: ILogger;

  client = createClient({
    subdomain: 'xxx',
    username: 'xxx@xxxxxx',
    token: 'xxxxxxxxxxxxxx', 
    throttle: true,
    // debug: true,
  });

  async listUsers() {
    return await this.client.users.get('users');
  }

  async listTicketAudit() {
    //const res = await this.client.ticketaudits.list(407036); //! 204 code with throttle enable
    const res = await this.client.ticketaudits.getAll('tickets/407036/audits'); //! 204 code with throttle enable
    this.logger.info(`res: ${JSON.stringify(res)}`);
    return res;
  }
}
```

**Expected Behavior**
I want to request over 100k resources with 500 api/minute.

**Actual Behavior**
when disable throttle, both methods work well and listTicketAudit got 3 items of pagination data; 
when enable throttle, listTicketAudit got `[{"statusCode":204,"result":null}]` but listUsers also work. 
![image](https://github.com/blakmatrix/node-zendesk/assets/27120235/5500eea0-c5ca-413c-a6e6-00d3c9859c95)

**Environment Information**
- `node-zendesk` version: 5.0.7
- Node.js version: v18.14.0
- Operating System: MacBook Pro 2019 with Sonama 14.1.1, intel Core i9
- Any other relevant software versions?

**Additional Context**

**Comment by blakmatrix** [comment]
Thank you for providing the detailed information regarding the issue with throttling in the `node-zendesk` library.

1. **Is this still an ongoing problem for you?**
2. **File Sizes:** What are the typical sizes of the files you are attempting to upload?
3. **Detailed Errors:** Could you provide more detailed error responses or logs to help us diagnose the problem better?

Regarding the specific issue you've described:

1. **Throttling Behavior:** When throttling is enabled, it appears that `listTicketAudit` is returning a 204 status code with no content, while `listUsers` works as expected.
2. **Usage Intent:** You mentioned wanting to request over 100k resources at 500 API requests per minute. Could you confirm if this is still the current requirement?

Any additional details, such as configurations or specific usage patterns, would be very helpful.

Thank you for your patience and cooperation.

**Comment by stealthbomber10** [comment]
Hi @blakmatrix . I don't think the latest comment addresses the issue. The code shows that "throttle" is a boolean flag https://github.com/blakmatrix/node-zendesk/blob/514199080d654bfbb5a6638fdee48e7a9a595809/src/index.js#L22

And enabling it results in the 204 result.

Additionally, the docs still say to enable it as a boolean flag:
- https://github.com/blakmatrix/node-zendesk/blob/514199080d654bfbb5a6638fdee48e7a9a595809/docs/guide/Guide/Advanced/throttling.md?plain=1#L3
- https://github.com/blakmatrix/node-zendesk/blob/514199080d654bfbb5a6638fdee48e7a9a595809/docs/guide/Guide/Advanced/endpoint-override.md?plain=1#L7
