### ISSUE TITLE
Mismatched types

### ISSUE THREAD

**Issue by zomchak-code** [blakmatrix/node-zendesk#398]
**Describe the Bug**
Types are not matching actual values returned

**Example Code**
```javascript
const ticket = await client.tickets.show(392005);
console.log({ id: ticket.id, response: ticket.response });
```
![Screenshot 2023-12-15 at 00 26 43](https://github.com/blakmatrix/node-zendesk/assets/127699216/62f1055d-d21e-4384-b5ce-e5c7753290cc)

**Expected Behavior**
Either `.id` reported as type error or following output: 
```javascript
{
  id: 392005,
  response: undefined
}
```

**Actual Behavior**
Either `.resource` reported as type error and following output: 
```javascript
{
  id: undefined,
  response: {
    json: [Function: json],
    status: 200,
    headers: {
      get: [Function: get]
    },
    statusText: "OK"
  }
}
```

**Environment Information**
- `node-zendesk` version: 5.0.7
- Node.js version: 20.2.0
- Operating System: MacOS
- Any other relevant software versions?

**Comment by mackstann** [comment]
I'm seeing something similar with the TS types. I'm making a `users.createOrUpdate` call. The types say it returns a `Promise<User>`. But when the promise resolves, I don't have a `User`, I have a wrapper object with `response` and `result` properties. `result` is of type `User`.

Paste of the method declaration in 5.0.9 from my `node_modules`:
```typescript
    /**
     * Creates or updates a user.
     * @param {object} user - The user details.
     * @returns {Promise<User>} The created or updated user's details.
     * @async
     * @see {@link https://developer.zendesk.com/api-reference/ticketing/users/users/#create-or-update-user}
     * @example
     * const user = await client.users.createOrUpdate({name: 'John Doe', email: 'john@example.com'});
     */
    createOrUpdate(user: object): Promise<User>;
```

Paste of the actual resolved value:

```javascript
{
  response: {
    json: [Function: json],
    status: 201,
    headers: { get: [Function: get] },
    statusText: 'Created'
  },
  result: {
    id: ...,
    ... other User properties ...
  }
}
```

**Comment by dschu-lab** [comment]
We're facing the exact issue as @mackstann. 
We currently type cast to get around this, but it is a bit hacky...
```ts
    const zendeskUser = (await this.zendesk.users.createOrUpdate({
      user: {
            // user data
      },
    })) as unknown as { result: ZendeskUser };
```

**Comment by binarypie** [comment]
I have the same issue with users.show where it expects to return a Promise<User> but the actual response value is Promise<{result: User}>

**Comment by jckw** [comment]
I just contributed to the bounty on this issue:

https://until.dev/bounty/blakmatrix/node-zendesk/398

The current bounty for completing it is $40.00 if it is closed within 30 days, and decreases after that.

Others can also contribute to the bounty to increase it. If the bounty is increased by a further $60, it's more likely that it will get closed.

This bounty is currently for @blakmatrix, but it can be made into a public bounty with their approval

**Comment by owenshaupt** [comment]
ditto — exactly what @mackstann is seeing returned is also returning for me when using `users.update`

**Comment by andoshin11** [comment]
any update on this?

**Comment by pano9000** [comment]
having the same issue with `users.update`.
If I recall correctly also similar thing with `organizations.showMany` was happening, where the types expect an array of numbers, while in reality it also seems to correctly accept a single number, *not* in an array.

**Comment by fahadshahid-rayn** [comment]
Having similar issue with `tickets.create`, the documentation/comments suggest some thing else for payload whereas the code is working with original ZendeskAPI payload with error for types.

![Screenshot 2024-11-12 at 3 31 36 PM](https://github.com/user-attachments/assets/79db36b9-e8aa-4dfc-bcc5-ce8d258e6f5f)
![Screenshot 2024-11-12 at 3 31 51 PM](https://github.com/user-attachments/assets/d0baaeca-bbce-43b0-985d-aebc5070cc1d)

In the documentation it suggests;
`const newTicket = await client.tickets.create({ subject: 'New ticket', description: 'Ticket description' });`

**Comment by fahadbshahid** [comment]
Having similar issue with `tickets.create`, the documentation/comments suggest some thing else for payload whereas the code is working with original ZendeskAPI payload with error for types.

![Screenshot 2024-11-12 at 3 31 36 PM](https://github.com/user-attachments/assets/79db36b9-e8aa-4dfc-bcc5-ce8d258e6f5f)
![Screenshot 2024-11-12 at 3 31 51 PM](https://github.com/user-attachments/assets/d0baaeca-bbce-43b0-985d-aebc5070cc1d)

In the documentation it suggests;
`const newTicket = await client.tickets.create({ subject: 'New ticket', description: 'Ticket description' });`

**Comment by blakmatrix** [comment]
Hi @fahadbshahid 

Thank you for reporting this issue and for your patience! After reviewing the current code and type definitions, it looks like we've resolved many mismatched types in recent updates. Based on what I can see in the latest version, the types should now align correctly with the documentation and payload structure.

It's possible this issue is due to using an outdated version of the library. Could you please try updating to the latest version and see if the issue persists?

If you still encounter the problem, feel free to open a new issue or, if you're comfortable, submit a PR with a fix. We appreciate your contributions and want to ensure everything works smoothly for you.

I'll go ahead and close this ticket for now to keep things tidy, but we're here if you need further help!

Best,
Farrin
