### ISSUE TITLE
socket hang up  error on attachments

### ISSUE THREAD

**Issue by kemaghraby** [blakmatrix/node-zendesk#408]
Hello, i'm using version 5.0.10 but i am getting socket hang up errors trying to perform attachments upload

This is an example of hat i am doing :

```
const file = Buffer.from('test', 'utf-8');

const response = zendeskClient.attachments.upload(file, {
  filename: 'test.txt',
  binary: true,
});

```

and i am always getting socket hang up when using  attachments upload method
Could you please advise on what can i do to overcome this issue?

**Comment by ollebergkvist** [comment]
Same issue...

**Comment by ganz14** [comment]
is there a way to upload the file from stream with holding it in buffer?

**Comment by blakmatrix** [comment]
Thank you for reporting this issue.

Is this still an ongoing problem for you?
What is the size of the file(s) you are attempting to upload?
Could you provide more detailed error responses or logs to help us diagnose the problem better?

This information will help us identify the cause and work towards a solution.
