### ISSUE TITLE
client.tickets.addTags() and tickets.updateTags() pass an empty response body 

### ISSUE THREAD

**Issue by terriann** [blakmatrix/node-zendesk#416]
**Describe the Bug**

The `client.tickets.addTags()` and `client.tickets.updateTags()` methods produce API requests with no body.

**Example Code**

This behavior can be reproduced with the sample code included in the repo.

```javascript
const ticketId = 12345;
const tags = ['tag1', 'tag2'];
await client.tickets.addTags(ticketId, tags);
```

```javascript
const ticketId = 12345;
const tags = ['tag1', 'tag2'];
await client.tickets.updateTags(ticketId, tags);
```

**Expected Behavior**

The array of tags past as the second argument should be included in the request body, resulting in the Zendesk API adding or replacing all tags, respectively.

For the examples above, the request body variable `body` in the `_rawRequest()` method in [client.js](https://github.com/blakmatrix/node-zendesk/blob/c2a85adcb17833f06ae3e0600f98188f4a88c4af/src/clients/client.js#L164-L167) should have the value`{tags:["tag1", "tag2"]}`.

https://github.com/blakmatrix/node-zendesk/blob/c2a85adcb17833f06ae3e0600f98188f4a88c4af/src/clients/client.js#L164-L167

Zendesk API resources:
* https://developer.zendesk.com/api-reference/ticketing/ticket-management/tags/#add-tags
* https://developer.zendesk.com/api-reference/ticketing/ticket-management/tags/#set-tags

**Actual Behavior**

For the examples above, the request body (`body`) in the `_rawRequest()` method in [client.js](https://github.com/blakmatrix/node-zendesk/blob/c2a85adcb17833f06ae3e0600f98188f4a88c4af/src/clients/client.js#L164-L167) has the value `false`.

This causes `client.tickets.updateTags()` to remove all the tags on a post, while `client.tickets.addTags()` results in no new tags being added. 

**Environment Information**
- `node-zendesk` version: 5.0.12
- Node.js version: v20.12.0

**Additional Context**

This seems to be a logical error in constructing the parameters passed to the `requestAll()` method in `addTags()` and `updateTags()` The final parameter passed should not be an array; it should be an object, like `{tags:["tag1", "tag2"]}` which would result in the object's value being passed as the body of the PUT or POST request.

The following changes seem to sort out the issue:

```diff
  async updateTags(ticketId, tags) {
-    return this.requestAll('POST', ['tickets', ticketId, 'tags'], tags);
+    return this.requestAll("POST", ["tickets", ticketId, "tags"], {
+      tags: tags,
+    });
  }
```

```diff
  async addTags(ticketId, tags) {
-    return this.requestAll('PUT', ['tickets', ticketId, 'tags'], tags);
+    return this.requestAll("PUT", ["tickets", ticketId, "tags"], {
+      tags: tags,
+    });
  }
```

This is in line with how other parts of the library pass the last argument in the `requestAll()` method:

https://github.com/blakmatrix/node-zendesk/blob/c2a85adcb17833f06ae3e0600f98188f4a88c4af/src/clients/core/triggers.js#L181-L185
https://github.com/blakmatrix/node-zendesk/blob/c2a85adcb17833f06ae3e0600f98188f4a88c4af/src/clients/core/automations.js#L146-L151

Similarly reported in #255

**Comment by blakmatrix** [comment]
@terriann  Thank you so much for your detailed bug report regarding the `client.tickets.addTags()` and `client.tickets.updateTags()` methods. Your thorough explanation and the suggested changes are incredibly helpful.

I appreciate the time you've taken to identify and propose a solution to this issue. It would be fantastic if you could submit a pull request with your changes. Your contribution would be a valuable addition to the project and would help other users who are encountering the same problem.

Once again, thank you for your contribution, and I look forward to your pull request!
