### ISSUE TITLE
Please update the the releases CHANGELOG to say remoteUri -> endpointUri

### ISSUE THREAD

**Issue by jjinux** [blakmatrix/node-zendesk#421]
**Describe the Bug**
In version 3.0.0, we used to pass remoteUri to the connection arguments. In 4.0.0, we started needing to use endpointUri. I read https://github.com/blakmatrix/node-zendesk/releases, but this was not clear, and it resulted in a mysterious `Zendesk ticket creation failed: Error: Request processing failed: Zendesk Error (401): Not Authorized`.

Note that my code was *not* passing subdomain because per https://blakmatrix.github.io/node-zendesk/guide/Guide/Advanced/endpoint-override.html, if you use endpointUri it overrides subdomain.

So, for those of us who weren't passing subdomain and hadn't renamed remoteUri to endpointUri, we ended up with the mysterious failure above.

It'd be great if you could update https://github.com/blakmatrix/node-zendesk/releases with this information. I can't find anywhere in the source code where that documentation exists, so I wasn't able to submit a patch myself.

**Expected Behavior**
Document that when upgrading to 4.0.0 or above, if you were passing remoteUri to your connection arguments, you need to change that to remoteUri.

**Actual Behavior**
When you try to run the code as before, you end up with a `Zendesk ticket creation failed: Error: Request processing failed: Zendesk Error (401): Not Authorized`.

**Environment Information**
- `node-zendesk` version: 4.0.0 (but, I'm not asking for changes to that code)
- Node.js version: 18
- Operating System: macOS
- Any other relevant software versions? N/A

**Additional Context**
I'm not asking for changes to the code. I'm only asking for a change to the documentation for version 4.0.0 on https://github.com/blakmatrix/node-zendesk/releases.

**Comment by jjinux** [comment]
Relevant commit: https://github.com/blakmatrix/node-zendesk/commit/ebb0dab2a35c8db070b6346a83e282cdd07f391d

**Comment by blakmatrix** [comment]
Thanks @jjinux

**Comment by jjinux** [comment]
Thanks for the fix!
