### ISSUE TITLE
The TypeScript version seems to be broken, even the examples don't compile

### ISSUE THREAD

**Issue by ipeychev** [blakmatrix/node-zendesk#426]
**Describe the Bug**
The types are broken, the TypeScript code doesn't compile. I took an example from `node_modules/node-zendesk/dist/types/clients/core/tickets.d.ts`. Note the `@example`:

```
* Create a new ticket.
* @example
     * const newTicket = await client.tickets.create({ subject: 'New ticket', description: 'Ticket description' });
     */
    create(ticket: CreateOrUpdateTicket): Promise<{
        result: Ticket;
    }>;
```

I took this code and created an app:

**Example Code**
```typescript
import { createClient } from "node-zendesk";

async function test123() {
  const client = createClient({});
  const newTicket = await client.tickets.create({ subject: 'New ticket', description: 'Ticket description' });
}
```

**Expected Behavior**
The code to compile successfully.

**Actual Behavior**
There is a compilation error:
```
Object literal may only specify known properties, and 'subject' does not exist in type 'CreateOrUpdateTicket'.ts(2353)
(property) subject: string
```

![Screenshot 2024-09-10 at 18 32 08](https://github.com/user-attachments/assets/f64d6efb-b32a-432c-8661-7f53b58f1060)

**Environment Information**
- `node-zendesk` version: 5.0.13
- Node.js version: v20.9.0
- Operating System: MacOS
- Any other relevant software versions?

**Additional Context**
```
"dependencies": {
    "node-zendesk": "^5.0.13",
    "typescript": "^5.6.2"
  }
```

Maybe the problem is in the TypeScript version?

**Comment by m-rolana** [comment]
I have it too

**Comment by kustomrtr** [comment]
Try importing this:
```javascript
import type { CreateOrUpdateTicket } from "node-zendesk/dist/types/clients/core/tickets"
```

and then adding the newly imported `CreateOrUpdateTicket` type to the object you're passing to the update function:
```javascript
await client.tickets.create({ subject: 'New ticket', description: 'Ticket description' } as CreateOrUpdateTicket);
```

**Comment by louis49** [comment]
Same here

**Comment by 7c** [comment]
same here, types and signatures do not match for some reason

**Comment by michal-boruczkowski** [comment]
Me too

**Comment by m-rolana** [comment]
@blakmatrix Made a PR with a fix https://github.com/blakmatrix/node-zendesk/pull/434 Would appreciate some attention if you have time :pray:
