### ISSUE TITLE
typo function call in macros

### ISSUE THREAD

**Issue by 7c** [blakmatrix/node-zendesk#433]
**Describe the Bug**
./src/clients/core/macros.js:    return this.gettAll(['macros', 'active']);
./src/clients/core/macros.js:    return this.gettAll(['macros', parameters]);
./src/clients/core/macros.js:    return this.gettAll(['macros', 'categories']);

it is pretty obvious and easy-to-fix bug, this should be this.getAll call instead of this.gettAll

**Comment by blakmatrix** [comment]
this should be fixed in latest release
