### ISSUE TITLE
tickets.exportAudit now a List

### ISSUE THREAD

**Issue by drobern** [blakmatrix/node-zendesk#52]
Hi,

I see that the callback of `exportAudit` is now a list.

I expected it to be the same as Zendesk doc: https://developer.zendesk.com/rest_api/docs/core/ticket_audits
This part is missing in the callback:
```json
{
  "previous_page": null,
  "next_page": null,
  "count": 5,
  "audits": ...
}
```

The previous version (about a year ago) conformed to the Zendesk doc. 

Is there a reason this changed?

btw, thanks for fixing the attachment upload issue, that's why I downloaded the latest version.

**Comment by drobern** [comment]
Maybe it wasn't clear?

The result is now a list, and seems to be missing the fields above as well.

I see the list resultList is as expected and returns all fields

Thanks

**Comment by blakmatrix** [comment]
tracking this down to https://github.com/blakmatrix/node-zendesk/commit/d7f24c3c14a798609488d668929fa2b3381f1f06

request was changed to requestAll for "Modified tickets/audits to fetch more than 100 audits, added a third jsonAPIName parameter in support of that"

@drobern can we close this or is there more action necessary?

**Comment by drobern** [comment]
Don't think this was my problem... here is the code that I was trying:
exports.getAudit = function(id, callback) {
    client.tickets.exportAudit(id, function (err, statusList, body, responseList, resultList) {
      if (err) {
        console.log("Error audit id?");
        return;
      } 
     callback(body);
    });
}

I always return 'body' for all other calls.. but for this one I have to return 'resultList'. This happened after  module update back in Jan 20.. I was running code from over 6 months earlier and body was working

**Comment by blakmatrix** [comment]
@drobern I'll have to take a look into this, the body was always reserved for the item for which you were soley trying to grab, in a way that would return as much as possible (but some people have hit `429` errors) while `rawResponse === arguments[3]` and `rawResult === arguments[4]`

Meanwhile along the way some one updated the `body` to be more useful from what I understand, returning just the results without the other metadata.

I'd suggest using `rawResult`... but I'm still a bit confused about the change from https://github.com/blakmatrix/node-zendesk/commit/d7f24c3c14a798609488d668929fa2b3381f1f06#diff-9fbce2e9fa85723cd2ead59e3caffd34R106 
@drobern can you revert that, ie. change in your code  `this.requestAll` to `this.request` does that fix the issue? (at least if you use `rawResult`?

**Comment by blakmatrix** [comment]
@drobern I was wondering if you got a chance to revert that change I mentioned a few days ago to your code?

**Comment by drobern** [comment]
@blakmatrix 

<code>rawResult</code> works using <code>this.requestAll</code>, it does not work using <code>this.request</code> (returns same list as body).

I'll leave this and use <code>rawResult</code> going forward.
