### ISSUE TITLE
Create Articles

### ISSUE THREAD

**Issue by lifasky** [blakmatrix/node-zendesk#55]
// ====================================== Creating Articles
Articles.prototype.create = function (article, cb) {
  this.request('POST', ['articles'], article, cb);
};

It should be
// ====================================== Creating Articles
Articles.prototype.create = function (sectionID, article, cb) {
  this.request('POST',['sections', sectionID, 'articles'], article, cb);
};

**Comment by nnabuuu** [comment]
I just checked zendesk's site https://developer.zendesk.com/rest_api/docs/help_center/articles and I do have made a mistake : ( Going to fix it soon

**Comment by lifasky** [comment]
The same for creating section, it should include a category ID. Thanks.
