### ISSUE TITLE
Unable to update articles to helpcenter

### ISSUE THREAD

**Issue by lifasky** [blakmatrix/node-zendesk#56]
After submiting, it just return the json data without updating.

**Comment by nnabuuu** [comment]
Any more details? I am just using it and it works.. Could you show me your code?

**Comment by nnabuuu** [comment]
According to zendesk's explanation at:

[https://developer.zendesk.com/rest_api/docs/help_center/articles#update-article ]()

```
These endpoints update article-level metadata such as its promotion status or sorting position. The endpoints do not update translation properties such as the article's title or body. See Translations.
```

Maybe you need to choose translation api to do the update.

My working code for this api:

```js
client.articles.update(202028690, {article:{ promoted: true}},function(err,code,res){

})
```

**Comment by lifasky** [comment]
Hi Xiaochen,

I think that is Zendesk API problem. Some articles are able to be updated,
some are not.
I sent a request to ask them for help. Thanks.

Best,
Gloria
