### ISSUE TITLE
setImage functionality

### ISSUE THREAD

**Issue by btraxinger** [blakmatrix/node-zendesk#59]
I have not seen a way to set an image for the user. Is this functionality included with node-zendesk?

**Comment by blakmatrix** [comment]
https://developer.zendesk.com/rest_api/docs/core/users#update-a-users-profile-image

let me see if I can whipsomething together for this, Zendesk has been updating thier api since I created this and while I've tried to stay on top somethings are still difficult :)

**Comment by blakmatrix** [comment]
SO you can already do:
Setting a remote image URL using `user.update`

```
curl -v -u {email_address}:{password} -X PUT -H "Content-Type: application/json" \
  -d '{"user": {"remote_photo_url": "http://link.to/profile/image.png"}}' \
  https://{subdomain}.zendesk.com/api/v2/users/{id}.json
```
but I'll have to add in the direct upload option.

**Comment by blakmatrix** [comment]
You can also upload an attachment to zendesk, then use the previous method to reference that file...

**Comment by blakmatrix** [comment]
This seems to be difficult with the current implementation to use the form method to upload.
