### ISSUE TITLE
Change Client Session

### ISSUE THREAD

**Issue by davidearlotto** [blakmatrix/node-zendesk#60]
Hi blakmatrix, 
I was trying to copy tickets from one instance to the other, so the workflow is this:
-Create a zendesk client to get the ticket I want;
-Create the new client to create the tickets in the other instances;
-Call the function (tickets.create);
Debugging I see I'm still querying the initial client. Is There any method to kill the session and create a new one live?
Thanks!!

**Comment by blakmatrix** [comment]
will be fixed in next version
