### ISSUE TITLE
Create Tickets

### ISSUE THREAD

**Issue by davidearlotto** [blakmatrix/node-zendesk#63]
Hi blakmatrix,
 in these days I faced an issue which is blocking me:
the create function, for ticket, groups, users, don' t work properly. Debugging them I notice, in the json sent, there is no body, and the ticket I'm passing, using a simple curl request, is created.
```js
         { method: 'POST',
           uri: 'https://our_domain.zendesk.com/api/v2/tickets.json',
           headers: 
                 { 'Content-Type': 'application/json',
                   Accept: 'application/json',
                   'User-Agent': 'node-zendesk/0.0.18 (node/0.10.25)',
                   Authorization: 'Basic    auth_string' },
           body: '{}' }
```
Can you please help me, at least to understand where should I work on your code?
Thanks 
Cheers!!

**Comment by blakmatrix** [comment]
What is the code your using look like? the user-create example works for me.

**Comment by davidearlotto** [comment]
Hi blakmatrix,

**Comment by davidearlotto** [comment]
Hi blakmatrix, 
my code is really simple, I just input a user/group/ticket to create it in this way:


   function createUser(User, ticket, key, cb){
	
	client.tickets.create(JSON.stringify(User),  function(err, req, result) {
	 
	  if (err) return handleError(err);
	  //console.log((result, null, 2, true));
	  User.id = result.id;
	  ticket[key] = User.id;
	  console.log("RESULT: "+result);
	  cb();
	});
    
	function handleError(err) {
		console.log(err);
		process.exit(-1);
	}	
      }


As JSON I have something like this:

     {
                "user": {
                    "name": "Davide Arlotto",
                    "email": "arlotto.davide@gmail.com",
                    "phone": null,
                    "time_zone": "Amsterdam",
                    "locale_id": 1,
                    "role": "end-user",
                    "ticket_restriction": "requested"
                }
            }


Thanks very much for the help!
Cheers!!

**Comment by blakmatrix** [comment]
@davidearlotto As far as I am aware, it looks like you are trying to make a ticket with the user object?
the spec is here https://developer.zendesk.com/rest_api/docs/core/tickets#request-parameters
and you can create a ticket sending this:
```js
var ticket = {
               "ticket":
                 {
                   "subject":"My printer is on fire!", 
                   "comment": { "body": "The smoke is very colorful." },
                   "submitter_id": 478932
                 }
             };
client.tickets.create(ticket,  function(err, req, result) {
  if (err) return handleError(err);
  console.log(JSON.stringify(result, null, 2, true));
});

function handleError(err) {
    console.log(err);
    process.exit(-1);
}
```

**Comment by blakmatrix** [comment]
@davidearlotto Are you still having issues?

**Comment by davidearlotto** [comment]
Actually not, your code works, something messy into mine. 
I actually change my focus for a while so I didn't had time to check it.
Thanks anyway.
Cheers

**Comment by davidearlotto** [comment]
I reopen it because the problem is still there in another way:
-If I create a stic variable as you did, I can create a ticket;
-If this ticket comes out of a JSON.stringify function I can't (the format and the data are the same):
    -I create a json: ticket.subject, ticket.description, ticket.comment;
    -I stringify it (I can see the same format you posted);
    -I create with the node zendesk module, but I got a bad request error.

Is that the stringify function that is not correct in this case?
Thanks
Cheers
