### ISSUE TITLE
Voice Channel Ticket Create

### ISSUE THREAD

**Issue by jeffdagala** [blakmatrix/node-zendesk#65]
Hi,

Does creating voice integration ticket supported?

https://developer.zendesk.com/rest_api/docs/voice-api/voice_integration

I tried to supply via_ids to 44 and the channel was API, although 45 and 46  (Phone Inbound and Outbound) value works well

**Comment by erikzrekz** [comment]
@blakmatrix ah, right. I don't use those other integrations, but I'll add them to this PR. That cool?

**Comment by blakmatrix** [comment]
awesome thanks, made those just so I could merge your changes cleanly thanks!
