### ISSUE TITLE
Working Group Request

### ISSUE THREAD

**Issue by blakmatrix** [blakmatrix/node-zendesk#68]
Hey, I'd like to get some help on this project, I'd like to get a Working Group of a minimum of 2 other heads to help drive this project along, We would have to commit meeting at least monthly (if there is anything to meet about) over skype/hangout or gitter. The objective is simply to help drive changes forward and get a regular set of eyes on the project.

**Comment by erikzrekz** [comment]
I'm interested in helping.

**Comment by nnabuuu** [comment]
I would like to offer some help : ) But please just consider me as an alternative candidate due to the Time Zone and GreatFireWall issue : (

**Comment by erikzrekz** [comment]
@blakmatrix any further momentum on this working group?

**Comment by blakmatrix** [comment]
@erikzrekz @nnabuuu I've been super busy the past few weeks, In early April I'll revisit this, maybe we should try and find some time to Skype/google hangout/watever, this WG is new for me, but I know this project needs to keep its momentum and I can' always provide that by myself when I get busy :)

**Comment by erikzrekz** [comment]
Totally. Just checking in.

**Comment by nnabuuu** [comment]
I will check the notification regularly~

**Comment by blakmatrix** [comment]
Hey Guys I'm reaching out to a few groups to see if we can get a few more people on board, I'd Ideally like to start with 5 but I'll settle with just one more if need be, or just @erikzrekz @nnabuuu @blakmatrix if absolutely necessary.

**Comment by blakmatrix** [comment]
@erikzrekz @nnabuuu I'd like to set up a google hangout/skype/whatever in the near future to get to know each other, set up permissions on github/npm, help define the working group (get a `Contributing.md` and `GOVERNANCE.md` up), and talk about the future/roadmap of the tool. 

I made a doodle s we can try and coordinate times, here http://doodle.com/qhwwfttutby2e654

(if there are any other interested feel free and signup on this doodle)

**Comment by nnabuuu** [comment]
Wow, I never used doodle before, so I'm learning how to use it : ) I just checked some time period at this weekend.

**Comment by blakmatrix** [comment]
@erikzrekz Sweet looks like we got a time to chat this upcomming weekend, Saturday May 9th, 7-8am PST.
I know of skype or google hangouts, they both work well for me but how about you two?

**Comment by erikzrekz** [comment]
@blakmatrix both work for me. My name is eriks.reks on Skype.

**Comment by nnabuuu** [comment]
Skype does not work for netizens living in Great Fire Wall : (

**Comment by blakmatrix** [comment]
@nnabuuu google hangout or some suggestions?

**Comment by nnabuuu** [comment]
Yes, hangouts works for me, though I still need an vpn to access it, but it requires less network traffic

**Comment by erikzrekz** [comment]
Google hangout works!

**Comment by blakmatrix** [comment]
https://plus.google.com/hangouts/_/g3tgnxddgh27nyognprtf6zlnaa
