### ISSUE TITLE
Subdomain parameter not working in Library mode

### ISSUE THREAD

**Issue by ckumar1** [blakmatrix/node-zendesk#80]
The client initialization code for getting the subdomain option `nconf.get('subdomain')` does not return the subdomain when it is set from the createClient method options:

``` javascript
var client = zendesk.createClient({
  username:  'test@gmail.com',
  token:     'testing_token',
  remoteUri: 'https://test.zendesk.com/api/v2',
  subdomain: 'wtp',
  helpcenter: true,
  debug: true,
  disableGlobalState: true
});
```

Replacing `nconf.get('subdomain')` with `options.stores.defaults.store.subdomain` seems to fix the issue.

https://github.com/blakmatrix/node-zendesk/blob/master/lib/client.js#L57

**Comment by blakmatrix** [comment]
Interesting...

I found that adding `nconf.defaults(options.stores.defaults.store);` after line https://github.com/blakmatrix/node-zendesk/blob/master/lib/client.js#L55 seems to do the trick... 


@erikzrekz do you think this will have any ramifications if we make this change? env/argv seem to take precedence when `disableGlobalState === true` we might be able to return to using `nconf.get('[option key]')` in `lib/client.js`... I must admit I'm getting a little confused about our usage of nconf as of late with the gravitation of what seems to be a phasing out of allowing `env` and `argv` in favor of a pure library.

**Comment by mzelmanovich** [comment]
I have yet to get helpcenter to work while in lib mode.

**Comment by erikzrekz** [comment]
@blakmatrix  No, I don't anticipate any ramifications from this. Seems okay.

And yeah, let's see how we can return to using `nconf.get('[option key]')`. I was solving for initializing multiple clients when I put together https://github.com/blakmatrix/node-zendesk/commit/f7633a654df7159eecf152fdcffa730aa0f38f83. But let me take a look in the upcoming days. Will report back.
