### ISSUE TITLE
Search.query escapes search term

### ISSUE THREAD

**Issue by ev-tt** [blakmatrix/node-zendesk#81]
Hello,

I want to do following query to search api:

```
var query = 'type:ticket+status<solved'
```

when I'm using search endpoint

```
client.search.query(query, cb)
```

actual request sent to server turns into 

```
/api/v2/search.json?query=type%3Aticket%2Bstatus%3Csolved
```

and cannot be processed by search api

However code below works ( in case somebody needs workaround):

```
client.search.requestAll('GET', ['search', '?query='+query], cb)
```

it sends correct request

```
/api/v2/search.json?query=type:ticket+status<solved
```

**Comment by erikzrekz** [comment]
@ev-tt thanks for the workaround.

Looks like we have some differences with how we're treating search. `/node-zendesk/lib/client/search.js` uses `this.request('GET', ['search', {query: searchTerm}], cb);};`

Other searches like `/node-zendesk/lib/client/organizations.js` use `this.requestAll('GET', ['*', 'search', params], cb);`

And like you mentioned, even the last example requires that the params user `?query=` to start. I'll mark this as our *Query Consistency/Improvement* issue.

We may also want to consider encoding some values (particularly emails) if they are included in the query string.

**Comment by erikzrekz** [comment]
@blakmatrix @nnabuuu I think we should stick with `requestAll` when searching. Which means we update the methods `search.query` and `search.queryAnonymous.`

Any further thoughts?

**Comment by markotom** [comment]
Any progress?
