### ISSUE TITLE
Undefined result: "Cannot read property 'next_page' of undefined"

### ISSUE THREAD

**Issue by emimvi** [blakmatrix/node-zendesk#83]
I have an application occasionally requesting a list of tickets from zendesk, in which i get the following error:

```
.../node_modules/node-zendesk/lib/client/client.js:134
    nextPage = result.next_page;
                     ^
TypeError: Cannot read property 'next_page' of undefined
    at .../node_modules/node-zendesk/lib/client/client.js:134:22
    at .../node_modules/node-zendesk/lib/client/client.js:258:12
    at checkRequestResponse (.../node_modules/node-zendesk/lib/client/client.js:227:10)
    at requestCallback (.../node_modules/node-zendesk/lib/client/client.js:235:3)
    at Request._callback (.../node_modules/node-zendesk/lib/client/client.js:105:5)
    at Request.self.callback (.../node_modules/node-zendesk/node_modules/request/request.js:373:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:169:7)
    at Request.<anonymous> (.../node_modules/node-zendesk/node_modules/request/request.js:1318:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:166:7)
```
Using node-zendesk v. 1.0.2

I'm not very much into http requests in general, but could a check be introduced on the result object - or am i doing something wrong?

Regards.

EDIT: I think it might be due to a request timeout, but i don't see how the error would slip past the error handling.

**Comment by erikzrekz** [comment]
@emimvi a fix was put in for this here https://github.com/blakmatrix/node-zendesk/commit/7743192c6fbd92287355ec0b1a0d20c6a108ccc8. 

Feel free to update your file or update the library.

**Comment by erikzrekz** [comment]
@emimvi a fix was put in for this here https://github.com/blakmatrix/node-zendesk/commit/7743192c6fbd92287355ec0b1a0d20c6a108ccc8. 

Feel free to update your file or update the library.

**Comment by erikzrekz** [comment]
@emimvi I'm opening this back up as I saw this again recently after https://github.com/blakmatrix/node-zendesk/commit/7743192c6fbd92287355ec0b1a0d20c6a108ccc8.

What methods are you using? Were you able to pinpoint which call returned this error?

**Comment by erikzrekz** [comment]
Does this https://github.com/blakmatrix/node-zendesk/pull/97 cover any of the methods you were using?

**Comment by emimvi** [comment]
No i only used the client.ticket.list function. At the time my internet connection was pretty bad, so the function often returned errors which i could then handle. The time it crashed though, it seems like the request returned neither an error or a result, which is kinda weird.

**Comment by erikzrekz** [comment]
Yeah, I double checked the error handling and put this in - https://github.com/blakmatrix/node-zendesk/pull/98. I am however still investigating to see what's up.

**Comment by erikzrekz** [comment]
@emimvi I'm going to close this out as I haven't heard about this issue in a while. Feel free to open back up if it persists.
