### ISSUE TITLE
Should we allow optional arguments or not?

### ISSUE THREAD

**Issue by nnabuuu** [blakmatrix/node-zendesk#90]
I am making up the missing HelpCenter endpoints, and I meet this one:

```
POST /api/v2/help_center/{locale}/sections/{id}/articles.json
```

Generally this end point act the same as:

```
POST /api/v2/help_center/sections/{id}/articles.json
```

The only different is the first one would put locale code in URL like `api/v2/help_center/**fr**/sections/{id}/articles.json`

And the second one need to specify the locale code in article object `{locale: 'fr'}`

So I would like to query you if we have a pattern for this condition.

I myself is using code like:

``` js
// ====================================== Creating Articles
Articles.prototype.create = function (/*Optional*/locale, sectionID, article, cb) {
  var args = Array.prototype.slice.call(arguments);

  if(args.length >= 4){
    this.request('POST', [locale, 'sections', sectionID, 'articles'], article, cb);
  }
  else{
    sectionID = args[0];
    article = args[1];
    cb = args[2];
    this.request('POST', ['sections', sectionID, 'articles'], article, cb);
  }
```

@blakmatrix @erikzrekz 
Could you propose any better format for this? I found section / category / article all facing this question.

**Comment by blakmatrix** [comment]
I've taken the form as shown here https://github.com/blakmatrix/node-zendesk/blob/master/lib/client/attachments.js#L15 
a bit more complex is https://github.com/blakmatrix/node-zendesk/blob/master/lib/client/useridentities.js#L31 - except with that one the format is the optional bit

When I worked at nodejitsu back in the day I used the form of this (https://github.com/nodejitsu/jitsu/blob/master/lib/jitsu/commands/env.js#L37-L46) for optionals note: we used the flatiron framework, utile was a utility library and simply utilize these mechanisms https://github.com/flatiron/utile/blob/master/lib/args.js

I personally prefer simplicity, utilization of an `options` object that can be passed allong as `{}` or `{locale: 'fr'}` but is explicit in requirement.

**Comment by blakmatrix** [comment]
Also regarding simplicity, for `GET /api/v2/help_center/{locale}/sections/{id}.json` We could also create a method named `createBySectionWithLocale` but I feel as if that is almost overly verbose and I'd personally use the option format over that.

**Comment by nnabuuu** [comment]
Using an `options` object would break the backward compatibility. 

Since in both end points we need to use `sectionID` to specify where the article belongs to, the prepositional phrase `bySection` could be omitted. I finally choose `createWithLocale` for this new end point. 

I am also thinking we can apply the same rule to name an end point: Methods like `listByUser` is where user need to pass `userID` to identify results, so they use preposition `By`. While `WithLocale` means the result is not only identified by `Locale` but also requires other information like `sectionID` in this example.

**Comment by erikzrekz** [comment]
Since the locale is mandatory when creating something new in the help center, I'm of the opinion that we just utilize the option object. Seems straightforward and included already in the post body. 

Plus the documentation reads: 
>You must specify an article title and locale. The locale can be omitted if it's specified in the URL.

@nnabuuu if this is the case and we choose to go this route, then we should disregard the create endpoints that have the locale defined and only use ones like `POST /api/v2/help_center/sections/{id}/articles.json.` 

Meanwhile, listing and updating should go unchanged and still have the `byLocale` methods.

**Comment by nnabuuu** [comment]
OK, let's do this: I will make 2 methods `byLocale` and `withLocale`, but I would add a warning message in `byLocale`, we wouldn't delete the `byLocale` method until a major version upgrade.
