### ISSUE TITLE
User Identity Update doesn't support updating values

### ISSUE THREAD

**Issue by BobDickinson** [blakmatrix/node-zendesk#91]
https://developer.zendesk.com/rest_api/docs/core/user_identities#update-a-given-user-identity

There are two modes of this command, one to update "verified" and one to update "value".  The current implementation does this:

```
UserIdentities.prototype.update = function (userID, userIDentityID, cb) {
    this.request('PUT', ['users', userID, 'identities', userIDentityID], {"identity": {"verified": true}}, cb);
};
```

which handles the first case.  I need to update the identity value, which does not appear to be supported.

**Comment by BobDickinson** [comment]
FWIW, I just did this in my client code:

    client.useridentities.updateValue = function (userID, userIDentityID, value, cb)
    {
        this.request('PUT', ['users', userID, 'identities', userIDentityID], { "identity": { "value": value } }, cb);
    };

**Comment by erikzrekz** [comment]
Cool. Thanks for writing this up. Marking as a bug/enhancement. Would you prefer that there was just one method for this instead of two?

**Comment by Shrutichhatbar** [comment]
Can I have an example of creation of user identities?
